# Generated by unbake. Do not edit; unbake regenerates it from config.toml and versions/.
# make check            build every version in one parallel graph and compare each ROM with the original
# make VERSION=<v> rom  build one version
# make setup            fetch and verify the compilers into tools/
# make verify           check the compilers, n64link and the original ROMs
# make V=1 ...          echo every command
# Without -jN make runs one job per core. Identical compiler inputs compile once (build/cas).
# Tools come from PATH (make, cpp, mips binutils, n64link, coreutils, curl, tar) or as
# make CPP=... AS=... LD=... N64LINK=... on the command line.
SHELL := /bin/sh
.SUFFIXES:
.DELETE_ON_ERROR:
.SECONDARY:
ifeq ($(filter -j%,$(MAKEFLAGS)),)
JOBS := $(shell nproc)
$(if $(JOBS),,$(error nproc printed no core count; run make -jN))
MAKEFLAGS += -j$(JOBS)
endif
Q = $(if $(filter 1,$(V)),,@)
NAME := RageWars
VERSIONS := de eu eu-x us us-rev1
ROMS := $(foreach v,$(VERSIONS),build/$v/$(NAME).z64)
CPP := cpp
AS := mips-linux-gnu-as
LD := mips-linux-gnu-ld
N64LINK := n64link
OBJCOPY := mips-linux-gnu-objcopy
ARMIPS := armips
INCLUDES := -Iinclude
CPPFLAGS := -P -undef -nostdinc -D_LANGUAGE_C -DF3DEX_GBI_2 -D__GNUC__=2
PREPROCESS_FLAGS = $(INCLUDES) -D__UNBAKE_STDARG_GCC=1 $(VERSION_DEFINES) $(CONSUMER)
ASSEMBLER_FLAGS := -march=vr4300 -mabi=32 -EB -G0 --no-pad-sections
HASM_ASFLAGS := -march=vr4300 -mabi=32 -EB --no-pad-sections
KIND := gnu
CC := tools/gcc-2.8.1-sn64/cc1
CODEGEN := -G0 -mips3 -O2 -mgas -meb -mcpu=VR4300 -mhard-float -mgp32 -mfp64 -mno-fix4300
COMPILER_INCLUDES := 
COMPILER_DEFINES := 
TRIM := 
UNIT_INCLUDES :=
UNIT_CODEGEN :=
UNIT_DEFINES :=
CONSUMER :=

.PHONY: all check verify setup clean rom
all: check

check: verify $(ROMS)
	@sha1sum -c $(foreach v,$(VERSIONS),versions/$v/$(NAME).sha1)

ifdef VERSION
ifeq ($(filter $(VERSION),$(VERSIONS)),)
$(error VERSION=$(VERSION) is not one of $(VERSIONS))
endif
endif
rom: $(if $(VERSION),build/$(VERSION)/$(NAME).z64)
	@$(if $(VERSION),,$(error make rom needs VERSION=<one of $(VERSIONS)>))sha1sum -c versions/$(VERSION)/$(NAME).sha1

verify:
	@sha256sum --quiet -c tools/compilers.sha256
	@test "$$($(N64LINK) --version)" = "$$(cat tools/n64link.version)" || { echo 'n64link: expected' "$$(cat tools/n64link.version)"; exit 1; }
	@sha1sum --quiet -c $(foreach v,$(VERSIONS),versions/$v/baserom.sha1)

setup:
	@mkdir -p tools/.downloads tools/gcc-2.7.2-kmc tools/.downloads/gcc-2.7.2-kmc-0
	@test -f tools/.downloads/ff3e299c1d952c0a5cb39f7790a208d0c547cf93986eb5607f820c935cedc288.tar.gz || curl -fsSL -o tools/.downloads/ff3e299c1d952c0a5cb39f7790a208d0c547cf93986eb5607f820c935cedc288.tar.gz https://github.com/decompals/mips-gcc-2.7.2/releases/download/main/gcc-2.7.2-linux.tar.gz
	@echo 'ff3e299c1d952c0a5cb39f7790a208d0c547cf93986eb5607f820c935cedc288  tools/.downloads/ff3e299c1d952c0a5cb39f7790a208d0c547cf93986eb5607f820c935cedc288.tar.gz' | sha256sum --quiet -c
	@tar -xzf tools/.downloads/ff3e299c1d952c0a5cb39f7790a208d0c547cf93986eb5607f820c935cedc288.tar.gz -C tools/.downloads/gcc-2.7.2-kmc-0
	@for f in $$(find tools/.downloads/gcc-2.7.2-kmc-0 -type f -name 'cc1'); do [ "$$(sha256sum < $$f | cut -c1-64)" = c4976e94ebf81d0ab1336f631fb752fbe6e0e0810e90a24da11e6ed1d5223b8a ] && cp $$f tools/gcc-2.7.2-kmc/cc1 && chmod 755 tools/gcc-2.7.2-kmc/cc1 && break; done
	@rm -rf tools/.downloads/gcc-2.7.2-kmc-0
	@mkdir -p tools/.downloads tools/gcc-2.8.1-sn64 tools/.downloads/gcc-2.8.1-sn64-0
	@test -f tools/.downloads/1156cf0d6a88a64c20e2a10fc9445d99cb9a38518f432b1669528dfa82ebb45f.tar.gz || curl -fsSL -o tools/.downloads/1156cf0d6a88a64c20e2a10fc9445d99cb9a38518f432b1669528dfa82ebb45f.tar.gz https://github.com/pmret/gcc-papermario/releases/download/master/linux.tar.gz
	@echo '1156cf0d6a88a64c20e2a10fc9445d99cb9a38518f432b1669528dfa82ebb45f  tools/.downloads/1156cf0d6a88a64c20e2a10fc9445d99cb9a38518f432b1669528dfa82ebb45f.tar.gz' | sha256sum --quiet -c
	@tar -xzf tools/.downloads/1156cf0d6a88a64c20e2a10fc9445d99cb9a38518f432b1669528dfa82ebb45f.tar.gz -C tools/.downloads/gcc-2.8.1-sn64-0
	@for f in $$(find tools/.downloads/gcc-2.8.1-sn64-0 -type f -name 'cc1'); do [ "$$(sha256sum < $$f | cut -c1-64)" = d1ddfe21dfa61840a83f833c8bd45ed7e2f606c3d9c351d2ec732fb6e4f97c89 ] && cp $$f tools/gcc-2.8.1-sn64/cc1 && chmod 755 tools/gcc-2.8.1-sn64/cc1 && break; done
	@rm -rf tools/.downloads/gcc-2.8.1-sn64-0
	@mkdir -p tools/.downloads tools/ido-5.3 tools/.downloads/ido-5.3-0
	@test -f tools/.downloads/ab5c741561f80913d58c8b074771f23941a3edd312505a8ebed6d1dfeb65e506.tar.gz || curl -fsSL -o tools/.downloads/ab5c741561f80913d58c8b074771f23941a3edd312505a8ebed6d1dfeb65e506.tar.gz https://github.com/decompals/ido-static-recomp/releases/download/v1.2/ido-5.3-recomp-linux.tar.gz
	@echo 'ab5c741561f80913d58c8b074771f23941a3edd312505a8ebed6d1dfeb65e506  tools/.downloads/ab5c741561f80913d58c8b074771f23941a3edd312505a8ebed6d1dfeb65e506.tar.gz' | sha256sum --quiet -c
	@tar -xzf tools/.downloads/ab5c741561f80913d58c8b074771f23941a3edd312505a8ebed6d1dfeb65e506.tar.gz -C tools/.downloads/ido-5.3-0
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'acpp'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 7bfdf2f79010eb95bd47e165036cac04a69e5f1290fde11736e5f6934f3e9189 ] && cp $$f tools/ido-5.3/acpp && chmod 755 tools/ido-5.3/acpp && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'as0'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 72670d53952459fe5ac463e8844182cf4df9f6ccf469826c82ca858fdd665564 ] && cp $$f tools/ido-5.3/as0 && chmod 755 tools/ido-5.3/as0 && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'as1'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 39c9750c189df37d4df0f33e5eddec9d4e743cbecad0326af3dda437826dc695 ] && cp $$f tools/ido-5.3/as1 && chmod 755 tools/ido-5.3/as1 && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'c++filt'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 60791cf1d07ba780a4e8aa25d53c741d4b7d5427f891f7287b1bed0b6ba3e665 ] && cp $$f tools/ido-5.3/c++filt && chmod 755 tools/ido-5.3/c++filt && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'cc'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 76d796c9591c9f5504949f85b29c32a6039a663791afe2f36f34ca18425b64d0 ] && cp $$f tools/ido-5.3/cc && chmod 755 tools/ido-5.3/cc && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'cfe'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 7033dfb267f39a6e5381c0769f4fc46bbde193cfec771314429d8367ace898f2 ] && cp $$f tools/ido-5.3/cfe && chmod 755 tools/ido-5.3/cfe && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'copt'); do [ "$$(sha256sum < $$f | cut -c1-64)" = e62a2a7276d2f9fa7f5daac25e01abe92cf4765173391cb0b616434c9c8122b3 ] && cp $$f tools/ido-5.3/copt && chmod 755 tools/ido-5.3/copt && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'crt1.o'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 95bd24880e95e102bbdf2a1cfa2e10d391cb57784a42db19afd609c0904aee28 ] && cp $$f tools/ido-5.3/crt1.o && chmod 755 tools/ido-5.3/crt1.o && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'crtn.o'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 62197e97a5e56e21c6a4e76ffe9f634cf90b47046ebe4841086108101ce496eb ] && cp $$f tools/ido-5.3/crtn.o && chmod 755 tools/ido-5.3/crtn.o && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'err.english.cc'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 6f2d777730f0a70328bb932c116c1c195da765cb9bbdee8c6d3eaf7d6ad77e78 ] && cp $$f tools/ido-5.3/err.english.cc && chmod 755 tools/ido-5.3/err.english.cc && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'ld'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 266c5a22192ce532a6dcdb7127c1da72faa37e7e71d44677ab91d723b8ed2113 ] && cp $$f tools/ido-5.3/ld && chmod 755 tools/ido-5.3/ld && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'libc.so'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 803f8b127194a79d92c5caea62fd39097be16d3fcd9870b4470123cebd5d27fe ] && cp $$f tools/ido-5.3/libc.so && chmod 755 tools/ido-5.3/libc.so && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'libc.so.1'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 803f8b127194a79d92c5caea62fd39097be16d3fcd9870b4470123cebd5d27fe ] && cp $$f tools/ido-5.3/libc.so.1 && chmod 755 tools/ido-5.3/libc.so.1 && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'libexc.so'); do [ "$$(sha256sum < $$f | cut -c1-64)" = b59bf75bcbff1526ad4e3b2b49b313788a6e4c97df5b69b4bc2ddbd6726c5864 ] && cp $$f tools/ido-5.3/libexc.so && chmod 755 tools/ido-5.3/libexc.so && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'libgen.so'); do [ "$$(sha256sum < $$f | cut -c1-64)" = bb66dea1242000f648e890252cbe47037310559cc0ecda8ed212c0e545bf8063 ] && cp $$f tools/ido-5.3/libgen.so && chmod 755 tools/ido-5.3/libgen.so && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'libm.so'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 8acc66c2d1315b90f38a280fe04a26d0e61b5ca377976ed5d7f88bb064bd2e35 ] && cp $$f tools/ido-5.3/libm.so && chmod 755 tools/ido-5.3/libm.so && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'strip'); do [ "$$(sha256sum < $$f | cut -c1-64)" = bf39eca7d4357b699d59077078c657c5af428b0e57d5dd7835c3d0f915e801bf ] && cp $$f tools/ido-5.3/strip && chmod 755 tools/ido-5.3/strip && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'ugen'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 1734564701d39db213d6fe9c8f2cff16b82b28939fb1418348de479b41b7ac72 ] && cp $$f tools/ido-5.3/ugen && chmod 755 tools/ido-5.3/ugen && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'ujoin'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 34a6fff6e693f8c9505777d2860b4795fe97a01e89ce8616f4a5b624b11c451d ] && cp $$f tools/ido-5.3/ujoin && chmod 755 tools/ido-5.3/ujoin && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'uld'); do [ "$$(sha256sum < $$f | cut -c1-64)" = bc85b7963ac978af5a8c5902d1c3b868c01b09839c4f7e5c36a77960cbf61744 ] && cp $$f tools/ido-5.3/uld && chmod 755 tools/ido-5.3/uld && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'umerge'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 96ea21c084f4d4765562cd030ba2c9f314f5aefdd180b82d22e1ab5126fca913 ] && cp $$f tools/ido-5.3/umerge && chmod 755 tools/ido-5.3/umerge && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'uopt'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 4e11956bdce9cac4c2934320cb29c55d1f3d3a0281ee594fafa5ebec88df4dd5 ] && cp $$f tools/ido-5.3/uopt && chmod 755 tools/ido-5.3/uopt && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'upas'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 7fa9be3c14bfe854bb539312af5f4f40c29b975996bdd6868f489f82fb427d5b ] && cp $$f tools/ido-5.3/upas && chmod 755 tools/ido-5.3/upas && break; done
	@for f in $$(find tools/.downloads/ido-5.3-0 -type f -name 'usplit'); do [ "$$(sha256sum < $$f | cut -c1-64)" = f539dced35b1cfb8385a1431d7a7e0bc5a3223ea4c8347c884a9de850d89ab3b ] && cp $$f tools/ido-5.3/usplit && chmod 755 tools/ido-5.3/usplit && break; done
	@rm -rf tools/.downloads/ido-5.3-0
	@mkdir -p tools/.downloads tools/ido-7.1 tools/.downloads/ido-7.1-0
	@test -f tools/.downloads/0d411696e178fcca34c31c3bf02011b928d7fd9c1fa7f8bf45070e0781b58e15.tar.gz || curl -fsSL -o tools/.downloads/0d411696e178fcca34c31c3bf02011b928d7fd9c1fa7f8bf45070e0781b58e15.tar.gz https://github.com/decompals/ido-static-recomp/releases/download/v1.2/ido-7.1-recomp-linux.tar.gz
	@echo '0d411696e178fcca34c31c3bf02011b928d7fd9c1fa7f8bf45070e0781b58e15  tools/.downloads/0d411696e178fcca34c31c3bf02011b928d7fd9c1fa7f8bf45070e0781b58e15.tar.gz' | sha256sum --quiet -c
	@tar -xzf tools/.downloads/0d411696e178fcca34c31c3bf02011b928d7fd9c1fa7f8bf45070e0781b58e15.tar.gz -C tools/.downloads/ido-7.1-0
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'NCC'); do [ "$$(sha256sum < $$f | cut -c1-64)" = d886205c468987e49d1b294cc01c3d6bc886a879f4babb2f5035728d1df6029b ] && cp $$f tools/ido-7.1/NCC && chmod 755 tools/ido-7.1/NCC && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'acpp'); do [ "$$(sha256sum < $$f | cut -c1-64)" = fad6d749179e4c037ebdca99687fed6d759d37ab070a419a3362daabd9e82d79 ] && cp $$f tools/ido-7.1/acpp && chmod 755 tools/ido-7.1/acpp && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'as0'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 6734d45b9b92de4766dda32b9da88148e5445f3c1a7ea4862b2cd3dec9991b9c ] && cp $$f tools/ido-7.1/as0 && chmod 755 tools/ido-7.1/as0 && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'as1'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 52160d61a732d209eed15e0ce6736eee23118e1c34ca5b9ec61474fe1a4011e3 ] && cp $$f tools/ido-7.1/as1 && chmod 755 tools/ido-7.1/as1 && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'cc'); do [ "$$(sha256sum < $$f | cut -c1-64)" = d886205c468987e49d1b294cc01c3d6bc886a879f4babb2f5035728d1df6029b ] && cp $$f tools/ido-7.1/cc && chmod 755 tools/ido-7.1/cc && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'cfe'); do [ "$$(sha256sum < $$f | cut -c1-64)" = c264f0c1f3ece0d15c2cd2ff73fff20381e98ed09f630c8087e24010e2a5ce1a ] && cp $$f tools/ido-7.1/cfe && chmod 755 tools/ido-7.1/cfe && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'edgcpfe'); do [ "$$(sha256sum < $$f | cut -c1-64)" = a2505f76d1e225fc6173459214ba5a200ae45dbbfd58c68930570dadaa853806 ] && cp $$f tools/ido-7.1/edgcpfe && chmod 755 tools/ido-7.1/edgcpfe && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'err.english.cc'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 1baa78a42fe732318b907b39e54ba602d7733b179995ba25f02a800d73638fea ] && cp $$f tools/ido-7.1/err.english.cc && chmod 755 tools/ido-7.1/err.english.cc && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'ugen'); do [ "$$(sha256sum < $$f | cut -c1-64)" = a8bcc5d4dad3b67428cde0dac6002c1e1ef3f98ea69746ff05300cdab913d227 ] && cp $$f tools/ido-7.1/ugen && chmod 755 tools/ido-7.1/ugen && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'ujoin'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 208bc5c76b64774ec2cfb29780f78cb3a4ecfbb143a74ca2c6c776a9f2c23e95 ] && cp $$f tools/ido-7.1/ujoin && chmod 755 tools/ido-7.1/ujoin && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'uld'); do [ "$$(sha256sum < $$f | cut -c1-64)" = c3386ae712ae203e1aafb0a1f042f098a2a5e4c8336b213329c525dd4ec43036 ] && cp $$f tools/ido-7.1/uld && chmod 755 tools/ido-7.1/uld && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'umerge'); do [ "$$(sha256sum < $$f | cut -c1-64)" = c2700570d04abd42634e567573d5a6ca983c27bb85ca965c845eb3b9cc6a3761 ] && cp $$f tools/ido-7.1/umerge && chmod 755 tools/ido-7.1/umerge && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'uopt'); do [ "$$(sha256sum < $$f | cut -c1-64)" = b21294d653fa414ba97413dc2e17c17bb417f7699166b330ed00a6a3723f03a5 ] && cp $$f tools/ido-7.1/uopt && chmod 755 tools/ido-7.1/uopt && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'upas'); do [ "$$(sha256sum < $$f | cut -c1-64)" = bfac232de2073a72e93d2836eea2c41e52f99252f973af4f94bc675088929495 ] && cp $$f tools/ido-7.1/upas && chmod 755 tools/ido-7.1/upas && break; done
	@for f in $$(find tools/.downloads/ido-7.1-0 -type f -name 'usplit'); do [ "$$(sha256sum < $$f | cut -c1-64)" = 83f0f4d50162e4f70503c2589cb3290b8ea252fa072ce7684e659dc061a0208e ] && cp $$f tools/ido-7.1/usplit && chmod 755 tools/ido-7.1/usplit && break; done
	@rm -rf tools/.downloads/ido-7.1-0
	@sha256sum --quiet -c tools/compilers.sha256

clean:
	rm -rf build/cas $(foreach v,$(VERSIONS),build/$v/src build/$v/units build/$v/hasm build/$v/data build/$v/resources build/$v/slices)

include $(foreach v,$(VERSIONS),versions/$v/slices.mk)
include units.mk

PREPROCESS_gnu = $(CPP) $(CPPFLAGS) $(PREPROCESS_FLAGS) src/$(*F).c -MMD -MP -MT $(@D)/$(*F).i -MF $(@D)/$(*F).d > $(@D)/$(*F).i
COMPILE_gnu = $(abspath $(CC)) -quiet $(CODEGEN) $(UNIT_CODEGEN) $(*F).i -o $(*F).s && $(N64LINK) asn64 --as $(AS) $(ASSEMBLER_FLAGS) $(*F).s -o $(*F).o
PREPROCESS_ido = $(abspath $(CC)) $(PREPROCESS_FLAGS) -M src/$(*F).c > $(@D)/$(*F).deps && sed 's|^[^:]*:|$(@D)/$(*F).i:|' $(@D)/$(*F).deps > $(@D)/$(*F).d && rm $(@D)/$(*F).deps && $(abspath $(CC)) $(PREPROCESS_FLAGS) -E src/$(*F).c > $(@D)/$(*F).i
COMPILE_ido = $(abspath $(CC)) -Wab,-r4300_mul $(CODEGEN) $(UNIT_CODEGEN) -c $(*F).i -o $(*F).o
VER = $(word 2,$(subst /, ,$@))
VERSION_DEFINES = $($(VER).DEFINES)
TOOLCHAIN := $(firstword $(shell cat tools/compilers.sha256 tools/n64link.version | sha1sum))
UNIT_KEY = printf '%s\n' '$(VER) $(*F)'; \
  $(PREPROCESS_$(KIND)) && \
  set -- $$(printf '%s\n' '$(TOOLCHAIN) $(subst $(CURDIR)/,,$(COMPILE_$(KIND)))' | \
    sha1sum - $(@D)/$(*F).i) && [ -n "$$3" ] && \
  { [ -f build/cas/$$1$$3.o ] || { (cd $(@D) && $(COMPILE_$(KIND))) && mv -f $(@D)/$(*F).o build/cas/$$1$$3.o; }; } && \
  if [ ! -f $(@D)/$(*F).key ] || [ "$$(cat $(@D)/$(*F).key)" != "$$1$$3" ]; then \
    printf '%s\n' $$1$$3 > $(@D)/$(*F).key; fi
LINK_BIN = $(LD) -T versions/$(VER)/$(NAME).ld --section-start=.text=$(firstword $(subst :, ,$($(VER).U.$(*F)))) \
  --oformat binary -o $@ $(@D)/$(*F).placed.o
UNIT_BIN = read key < $< && \
  $(N64LINK) place build/cas/$$key.o -o $(@D)/$(*F).placed.o --rom $($(VER).BASEROM) --text $($(VER).U.$(*F)) \
  $(addprefix --map ,$($(VER).MAP)) --symbols versions/$(VER)/symbols.ld $(TRIM) && \
  $(LINK_BIN)
HASM_BIN = printf '%s\n' '$(VER) $(*F)'; \
  $(AS) $(HASM_ASFLAGS) -o $(@D)/$(*F).o $< && \
  $(N64LINK) place $(@D)/$(*F).o -o $(@D)/$(*F).placed.o --rom $($(VER).BASEROM) --text $($(VER).U.$(*F)) \
  $(addprefix --map ,$($(VER).MAP)) --symbols versions/$(VER)/symbols.ld --trim && \
  $(LINK_BIN)
DATA_BIN = read key < $< && \
  cp build/cas/$$key.o $(@D)/$(*F).o && \
  $(OBJCOPY) --set-section-flags .rdata=alloc,load,readonly,data,contents \
    --set-section-flags .rodata=alloc,load,readonly,data,contents \
    --set-section-flags .data=alloc,load,data,contents \
    --set-section-flags .sdata=alloc,load,data,contents $(@D)/$(*F).o && \
  $(LD) -EB -T versions/$(VER)/$(NAME).data.ld \
    --section-start=.data=$(firstword $(subst :, ,$($(VER).D.$(*F)))) \
    -o $(@D)/$(*F).elf $(@D)/$(*F).o && \
  $(OBJCOPY) -O binary --only-section=.data $(@D)/$(*F).elf $@ && \
  [ "$$(wc -c < $@)" -eq $$(( $(word 3,$(subst :, ,$($(VER).D.$(*F)))) )) ]
RESOURCE_NAME = $(basename $(notdir $@))
RESOURCE_BIN = $(AS) $($(VER).R.$(RESOURCE_NAME).ASFLAGS) -o $(@D)/$(RESOURCE_NAME).o $< && \
  $(LD) -EB -T versions/$(VER)/resources/$(RESOURCE_NAME).ld \
    -o $(@D)/$(RESOURCE_NAME).elf $(@D)/$(RESOURCE_NAME).o && \
  $(OBJCOPY) -O binary --only-section=.resource $(@D)/$(RESOURCE_NAME).elf $@ && \
  [ "$$(wc -c < $@)" -eq $$(( $(word 3,$(subst :, ,$($(VER).R.$(RESOURCE_NAME)))) )) ]
SLICE = dd if=$($(VER).BASEROM) of=$@ bs=65536 iflag=skip_bytes,count_bytes status=none \
  skip=$(word 1,$($(VER).S.$(*F))) count=$(word 2,$($(VER).S.$(*F)))

define VERSION_RULES
build/$1/src/%.i: src/%.c Makefile units.mk | verify build/$1/src build/cas
	$$(Q)$$(UNIT_KEY)
build/$1/src/%.key: build/$1/src/%.i
	$$(Q)test -f $$@ || { $$(UNIT_KEY); }
build/$1/units/%.bin: build/$1/src/%.key versions/$1/symbols.ld versions/$1/$$(NAME).ld | build/$1/units
	$$(Q)$$(UNIT_BIN)
build/$1/hasm/%.bin: src/%.s Makefile versions/$1/symbols.ld versions/$1/$$(NAME).ld | build/$1/hasm
	$$(Q)$$(HASM_BIN)
build/$1/data/%.bin: build/$1/src/%.key versions/$1/slices.mk \
  versions/$1/symbols.ld versions/$1/$$(NAME).data.ld | build/$1/data
	$$(Q)$$(DATA_BIN)
build/$1/slices/%.bin: $$($1.BASEROM) versions/$1/slices.mk | build/$1/slices
	$$(Q)$$(SLICE)
build/$1/$$(NAME).z64: $$($1.PIECES)
	$$(Q)printf '%s\n' '$1 rom'; cat $$($1.PIECES) > $$@
build/$1/src build/$1/units build/$1/hasm build/$1/data build/$1/resources build/$1/slices:
	$$(Q)mkdir -p $$@
endef
$(foreach v,$(VERSIONS),$(eval $(call VERSION_RULES,$v)))
build/cas:
	$(Q)mkdir -p $@

-include $(wildcard build/*/src/*.d)
