# Generated by unbake. Do not edit; unbake regenerates it from config.toml and versions/.
build/%/src/func_8021836C_de.key build/%/units/func_8021836C_de.bin: UNIT_CODEGEN := -fno-strength-reduce
build/%/src/func_80218E98_de.key build/%/units/func_80218E98_de.bin: UNIT_CODEGEN := -fno-strength-reduce
