#ifndef UNBAKE_SPAN_16E000_CODE_80405454_H
#define UNBAKE_SPAN_16E000_CODE_80405454_H
#include "common/types.h"
#include "span_16E000/types.h"
#include "../types.h"
struct Menu_func_804066BC_de;
struct Menu_func_804066BC_de;
typedef struct Menu_func_804066BC_de Menu_func_804066BC_de;

/* unbake evidence input: c3RydWN0IE1lbnVfZnVuY184MDQwNjZCQ19kZTsKdHlwZWRlZiBzdHJ1Y3QgTWVudV9mdW5jXzgwNDA2NkJDX2RlIE1lbnVfZnVuY184MDQwNjZCQ19kZTsK */

struct Menu_func_804085E0_de;
struct Menu_func_804085E0_de;
typedef struct Menu_func_804085E0_de Menu_func_804085E0_de;

/* unbake evidence input: c3RydWN0IE1lbnVfZnVuY184MDQwODVFMF9kZTsKdHlwZWRlZiBzdHJ1Y3QgTWVudV9mdW5jXzgwNDA4NUUwX2RlIE1lbnVfZnVuY184MDQwODVFMF9kZTsK */

struct Menu_func_80408C4C_de;
struct Menu_func_80408C4C_de;
typedef struct Menu_func_80408C4C_de Menu_func_80408C4C_de;

/* unbake evidence input: c3RydWN0IE1lbnVfZnVuY184MDQwOEM0Q19kZTsKdHlwZWRlZiBzdHJ1Y3QgTWVudV9mdW5jXzgwNDA4QzRDX2RlIE1lbnVfZnVuY184MDQwOEM0Q19kZTsK */

struct PakRecord;
struct PakRecord;
typedef struct PakRecord PakRecord;

/* unbake evidence input: c3RydWN0IFBha1JlY29yZDsKdHlwZWRlZiBzdHJ1Y3QgUGFrUmVjb3JkIFBha1JlY29yZDsK */

struct SharedPlayer_func_80408C4C_de;
struct SharedPlayer_func_80408C4C_de;
typedef struct SharedPlayer_func_80408C4C_de SharedPlayer_func_80408C4C_de;

/* unbake evidence input: c3RydWN0IFNoYXJlZFBsYXllcl9mdW5jXzgwNDA4QzRDX2RlOwp0eXBlZGVmIHN0cnVjdCBTaGFyZWRQbGF5ZXJfZnVuY184MDQwOEM0Q19kZSBTaGFyZWRQbGF5ZXJfZnVuY184MDQwOEM0Q19kZTsK */

struct Shared_func_804069F4_S1;
struct Shared_func_804069F4_S1;
typedef struct Shared_func_804069F4_S1 Shared_func_804069F4_S1;

/* unbake evidence input: c3RydWN0IFNoYXJlZF9mdW5jXzgwNDA2OUY0X1MxOwp0eXBlZGVmIHN0cnVjdCBTaGFyZWRfZnVuY184MDQwNjlGNF9TMSBTaGFyZWRfZnVuY184MDQwNjlGNF9TMTsK */

struct func_80408C78_S1;
struct func_80408C78_S1;
typedef struct func_80408C78_S1 func_80408C78_S1;

/* unbake evidence input: c3RydWN0IGZ1bmNfODA0MDhDNzhfUzE7CnR5cGVkZWYgc3RydWN0IGZ1bmNfODA0MDhDNzhfUzEgZnVuY184MDQwOEM3OF9TMTsK */

struct Shape_typemap_110;
struct func_80405CDC_S1;
struct func_80405CDC_S2;
struct Shape_typemap_110;
struct func_80405CDC_S1;
struct func_80405CDC_S2;
#ifndef UNBAKE_FUNC_80405CDC_DE_H
#define UNBAKE_FUNC_80405CDC_DE_H


struct func_80405CDC_S1;
typedef struct func_80405CDC_S1 func_80405CDC_S1;
typedef struct func_80405CDC_S2 func_80405CDC_S2;

struct func_80405CDC_S2;





struct func_80405CDC_S1 {
    char pad0[0x4];
    struct Shape_typemap_110 unk4;
};
struct func_80405CDC_S2 {
    char pad0[0x8];
    struct Shape_typemap_110 unk8;
};
#endif

/* unbake evidence input: c3RydWN0IFNoYXBlX3R5cGVtYXBfMTEwOwpzdHJ1Y3QgZnVuY184MDQwNUNEQ19TMTsKc3RydWN0IGZ1bmNfODA0MDVDRENfUzI7CiNpZm5kZWYgVU5CQUtFX0ZVTkNfODA0MDVDRENfREVfSAojZGVmaW5lIFVOQkFLRV9GVU5DXzgwNDA1Q0RDX0RFX0gKCgpzdHJ1Y3QgZnVuY184MDQwNUNEQ19TMTsKdHlwZWRlZiBzdHJ1Y3QgZnVuY184MDQwNUNEQ19TMSBmdW5jXzgwNDA1Q0RDX1MxOwp0eXBlZGVmIHN0cnVjdCBmdW5jXzgwNDA1Q0RDX1MyIGZ1bmNfODA0MDVDRENfUzI7CgpzdHJ1Y3QgZnVuY184MDQwNUNEQ19TMjsKCgoKCgpzdHJ1Y3QgZnVuY184MDQwNUNEQ19TMSB7CiAgICBjaGFyIHBhZDBbMHg0XTsKICAgIHN0cnVjdCBTaGFwZV90eXBlbWFwXzExMCB1bms0Owp9OwpzdHJ1Y3QgZnVuY184MDQwNUNEQ19TMiB7CiAgICBjaGFyIHBhZDBbMHg4XTsKICAgIHN0cnVjdCBTaGFwZV90eXBlbWFwXzExMCB1bms4Owp9OwojZW5kaWYK */

struct Owner_func_804066BC_de;
struct Owner_func_804066BC_de;
struct Owner_func_804066BC_de {
    char pad0[0x328];
    s32 flags;
};

/* unbake evidence input: c3RydWN0IE93bmVyX2Z1bmNfODA0MDY2QkNfZGU7CnN0cnVjdCBPd25lcl9mdW5jXzgwNDA2NkJDX2RlIHsKICAgIGNoYXIgcGFkMFsweDMyOF07CiAgICBzMzIgZmxhZ3M7Cn07Cg== */

struct Menu_func_804066BC_de;
struct Owner_func_804066BC_de;
struct Menu_func_804066BC_de;
struct Owner_func_804066BC_de;
struct Menu_func_804066BC_de {
    char pad0[0xC];
    struct Owner_func_804066BC_de *owner;
    char pad10[0xC];
    func_8024795C_S2 *player;
    func_80242278_S1 *slot;
};

/* unbake evidence input: c3RydWN0IE1lbnVfZnVuY184MDQwNjZCQ19kZTsKc3RydWN0IE93bmVyX2Z1bmNfODA0MDY2QkNfZGU7CnN0cnVjdCBNZW51X2Z1bmNfODA0MDY2QkNfZGUgewogICAgY2hhciBwYWQwWzB4Q107CiAgICBzdHJ1Y3QgT3duZXJfZnVuY184MDQwNjZCQ19kZSAqb3duZXI7CiAgICBjaGFyIHBhZDEwWzB4Q107CiAgICBmdW5jXzgwMjQ3OTVDX1MyICpwbGF5ZXI7CiAgICBmdW5jXzgwMjQyMjc4X1MxICpzbG90Owp9Owo= */

struct Menu_func_804085E0_de;
struct Menu_func_804085E0_de;
struct Menu_func_804085E0_de {
    char pad0[0x1C];
    SharedPlayer_func_8022A398_de *player;
    func_80242278_S1 *slot;
};

/* unbake evidence input: c3RydWN0IE1lbnVfZnVuY184MDQwODVFMF9kZTsKc3RydWN0IE1lbnVfZnVuY184MDQwODVFMF9kZSB7CiAgICBjaGFyIHBhZDBbMHgxQ107CiAgICBTaGFyZWRQbGF5ZXJfZnVuY184MDIyQTM5OF9kZSAqcGxheWVyOwogICAgZnVuY184MDI0MjI3OF9TMSAqc2xvdDsKfTsK */

struct Body;
struct Character;
struct Controller;
struct Controls;
struct Ctrl;
struct Held;
struct Mode;
struct Model;
struct Mount;
struct Profile_func_80408C4C_de;
struct Record;
struct Rider;
struct Settings;
struct SharedPlayer_func_80408C4C_de;
struct Shared_Body;
struct Shared_Hud;
struct Shared_Model;
struct Shared_Profile;
struct Shared_StateInfo;
struct Shared_Voice;
struct StateInfo;
struct TeamInfo;
struct View;
struct Body;
struct Character;
struct Controller;
struct Controls;
struct Ctrl;
struct Held;
struct Mode;
struct Model;
struct Mount;
struct Profile_func_80408C4C_de;
struct Record;
struct Rider;
struct Settings;
struct SharedPlayer_func_80408C4C_de;
struct Shared_Body;
struct Shared_Hud;
struct Shared_Model;
struct Shared_Profile;
struct Shared_StateInfo;
struct Shared_Voice;
struct StateInfo;
struct TeamInfo;
struct View;
struct SharedPlayer_func_80408C4C_de {
    union {
        struct {
            u8 unk0[24];
        } view0_0;
        struct {
            u8 pad0[24];
        } view0_1;
        struct {
            char pad[0x3];
            u8 team;
        } view3_2;
        struct {
            char pad[0x8];
            Vec3 unk8;
        } view8_2;
        struct {
            char pad[0x8];
            Vec3 pos;
        } view8_3;
        struct {
            char pad[0x8];
            Vec3 position;
        } view8_4;
        struct {
            char pad[0x14];
            struct Shared_Model * model;
        } view14_6;
        struct { char pad[8]; s32 positionWords[3]; } positionBits;
    } views0;
    union {
        struct {
            char * unk18;
        } view18_0;
        struct {
            char * track;
        } view18_1;
        struct {
            struct Model * model;
        } view18_2;
        struct {
            struct Body * body;
        } view18_3;
        struct {
            struct Character * character;
        } view18_4;
        struct {
            struct Shared_Body * body;
        } view18_5;
    } views18;
    union {
        struct {
            u8 unk1C[344];
        } view1C_0;
        struct {
            u8 pad1[344];
        } view1C_1;
        struct {
            char pad[0x4];
            f32 velY;
        } view20_2;
        struct {
            char pad[0x1C];
            s32 unk38;
        } view38_2;
        struct {
            char pad[0x1C];
            s32 flags;
        } view38_3;
        struct {
            char pad[0x24];
            f32 unk40;
        } view40_5;
        struct {
            char pad[0x40];
            Shared_Quad unk5C;
        } view5C_6;
        struct {
            char pad[0x50];
            f32 unk6C;
        } view6C_4;
        struct {
            char pad[0x50];
            f32 heading;
        } view6C_5;
        struct {
            char pad[0x50];
            f32 yaw;
        } view6C_9;
        struct {
            char pad[0xC8];
            u16 unkE4;
        } viewE4_6;
        struct {
            char pad[0xC8];
            u16 kind;
        } viewE4_7;
        struct {
            char pad[0xE4];
            s32 unk100;
        } view100_8;
        struct {
            char pad[0xE4];
            s32 flags;
        } view100_9;
        struct {
            char pad[0xE8];
            f32 unk104;
        } view104_10;
        struct {
            char pad[0xE8];
            f32 idleTime;
        } view104_11;
        struct {
            char pad[0xEC];
            s16 anim;
        } view108_16;
        struct {
            char pad[0xF2];
            s8 unk10E;
        } view10E_12;
        struct {
            char pad[0xF2];
            s8 idle;
        } view10E_13;
        struct {
            char pad[0xF2];
            s8 replaying;
        } view10E_14;
        struct {
            char pad[0xF2];
            s8 animPending;
        } view10E_20;
        struct {
            char pad[0x154];
            char unk170[100];
        } view170_15;
        struct {
            char pad[0x154];
            char body[100];
        } view170_16;
        struct {
            char pad[0x154];
            s32 unk170;
        } view170_23;
        struct {
            char pad[0x158];
            s32 unk174;
        } view174_17;
        struct {
            char pad[0x15C];
            u8 unk178[740];
        } view178_18;
        struct {
            char pad[0x15C];
            u8 pad2[740];
        } view178_19;
        struct {
            char pad[0x1B8];
            f32 unk1D4;
        } view1D4_20;
        struct {
            char pad[0x1B8];
            f32 holdTime;
        } view1D4_21;
        struct {
            char pad[0x1BC];
            struct SharedPlayer_func_80408C4C_de * unk1D8;
        } view1D8_22;
        struct {
            char pad[0x1BC];
            struct SharedPlayer_func_80408C4C_de * self;
        } view1D8_23;
        struct {
            char pad[0x1BC];
            struct SharedPlayer_func_80408C4C_de * f1D8;
        } view1D8_24;
        struct {
            char pad[0x1BC];
            void * unk1D8;
        } view1D8_32;
        struct {
            char pad[0x244];
            Vec3 unk260;
        } view260_25;
        struct {
            char pad[0x244];
            Vec3 muzzle;
        } view260_26;
        struct {
            char pad[0x2CC];
            char unk2E8[368];
        } view2E8_27;
        struct {
            char pad[0x2CC];
            char weapon[368];
        } view2E8_28;
        struct {
            char pad[0x2CC];
            Shared_Emitter emitter;
        } view2E8_37;
        struct {
            char pad[0x43C];
            char unk458[384];
        } view458_29;
        struct {
            char pad[0x43C];
            char ammo[384];
        } view458_30;
        struct {
            char pad[0x43C];
            s32 unk458;
        } view458_40;
        struct {
            char pad[0x440];
            s32 unk45C;
        } view45C_31;
        struct {
            char pad[0x444];
            u8 unk460[376];
        } view460_32;
        struct {
            char pad[0x444];
            u8 pad3[376];
        } view460_33;
        struct {
            char pad[0x468];
            struct Shared_Voice * voice;
        } view484_44;
        struct {
            char pad[0x470];
            s8 unk48C;
        } view48C_34;
        struct {
            char pad[0x470];
            s8 state;
        } view48C_35;
        struct {
            char pad[0x4A4];
            void * unk4C0;
        } view4C0_47;
        struct {
            char pad[0x507];
            s8 unk523;
        } view523_36;
        struct {
            char pad[0x507];
            s8 busy;
        } view523_37;
        struct {
            char pad[0x578];
            s32 unk594;
        } view594_38;
        struct {
            char pad[0x578];
            s32 gear;
        } view594_39;
        struct {
            char pad[0x578];
            s32 mode;
        } view594_40;
        struct {
            char pad[0x584];
            f32 unk5A0;
        } view5A0_41;
        struct {
            char pad[0x584];
            f32 charge;
        } view5A0_42;
        struct {
            char pad[0x5B4];
            s32 unk5D0;
        } view5D0_43;
        struct {
            char pad[0x5B4];
            s32 f5D0;
        } view5D0_44;
        struct {
            char pad[0x5B8];
            s32 unk5D4;
        } view5D4_45;
        struct {
            char pad[0x5B8];
            s32 slot;
        } view5D4_46;
        struct {
            char pad[0x5B8];
            s32 profile;
        } view5D4_47;
        struct {
            char pad[0x5B8];
            s32 f5D4;
        } view5D4_48;
    } views1C;
    union {
        struct {
            struct Record * unk5D8;
        } view5D8_0;
        struct {
            struct Record * record;
        } view5D8_1;
        struct {
            struct Controls * controls;
        } view5D8_2;
        struct {
            struct TeamInfo * teamInfo;
        } view5D8_3;
        struct {
            struct Ctrl * ctrl;
        } view5D8_4;
        struct {
            unsigned char * info;
        } view5D8_5;
        struct {
            struct Profile_func_80408C4C_de * profile;
        } view5D8_6;
        struct {
            struct Settings * settings;
        } view5D8_7;
        struct {
            s32 f5D8;
        } view5D8_8;
        struct {
            struct Shared_Profile * profile;
        } view5D8_9;
    } views5D8;
    union {
        struct {
            void * unk5DC;
        } view5DC_0;
        struct {
            void * view;
        } view5DC_1;
        struct {
            struct View * view;
        } view5DC_2;
        struct {
            u8 pad4[8];
        } view5DC_3;
        struct {
            void * entity;
        } view5DC_4;
        struct {
            struct Rider * rider;
        } view5DC_5;
        struct {
            char * storage;
        } view5DC_6;
        struct {
            char * messages;
        } view5DC_7;
        struct {
            struct Shared_Hud * hud;
        } view5DC_8;
        struct {
            char pad[0x4];
            s32 unk5E0;
        } view5E0_8;
        struct {
            char pad[0x4];
            s32 state;
        } view5E0_9;
        struct {
            char pad[0x4];
            s32 slot;
        } view5E0_10;
    } views5DC;
    union {
        struct {
            s32 unk5E4;
        } view5E4_0;
        struct {
            s32 active;
        } view5E4_1;
        struct {
            s32 health;
        } view5E4_2;
        struct {
            s32 alive;
        } view5E4_3;
        struct {
            s32 holding;
        } view5E4_4;
    } views5E4;
    union {
        struct {
            u8 unk5E8[3140];
        } view5E8_0;
        struct {
            u8 pad5[3140];
        } view5E8_1;
        struct {
            char pad[0x2];
            s16 unk5EA;
        } view5EA_2;
        struct {
            char pad[0x2];
            s16 respawns;
        } view5EA_3;
        struct {
            char pad[0x2];
            s16 runType;
        } view5EA_4;
        struct {
            char pad[0x4];
            s32 unk5EC;
        } view5EC_5;
        struct {
            char pad[0x4];
            s32 model;
        } view5EC_6;
        struct {
            char pad[0x4];
            s32 spawnPoint;
        } view5EC_7;
        struct {
            char pad[0x4];
            s32 f5EC;
        } view5EC_8;
        struct {
            char pad[0x8];
            s32 unk5F0;
        } view5F0_9;
        struct {
            char pad[0x8];
            s32 f5F0;
        } view5F0_10;
        struct {
            char pad[0xC];
            s16 unk5F4[4];
        } view5F4_11;
        struct {
            char pad[0xC];
            s16 ammo[4];
        } view5F4_12;
        struct {
            char pad[0xC];
            s16 ammo[3];
        } view5F4_13;
        struct {
            char pad[0x1A];
            Shared_Slot slots[22];
        } view602_14;
        struct {
            char pad[0x46];
            s16 unk62E;
        } view62E_13;
        struct {
            char pad[0x46];
            s16 weapon;
        } view62E_14;
        struct {
            char pad[0x46];
            s16 character;
        } view62E_17;
        struct {
            char pad[0x68];
            s16 unk650;
        } view650_15;
        struct {
            char pad[0x68];
            s16 state;
        } view650_16;
        struct {
            char pad[0x68];
            s16 action;
        } view650_17;
        struct {
            char pad[0x68];
            s16 mode;
        } view650_18;
        struct {
            char pad[0x6A];
            s16 unk652;
        } view652_19;
        struct {
            char pad[0x6A];
            s16 previous;
        } view652_20;
        struct {
            char pad[0x6A];
            s16 pad652;
        } view652_24;
        struct {
            char pad[0x6C];
            s16 prevState;
        } view654_25;
        struct {
            char pad[0x6E];
            s16 pad656;
        } view656_26;
        struct {
            char pad[0x70];
            f32 unk658;
        } view658_21;
        struct {
            char pad[0x70];
            f32 counter;
        } view658_22;
        struct {
            char pad[0x70];
            f32 stride;
        } view658_23;
        struct {
            char pad[0x70];
            f32 swimTime;
        } view658_24;
        struct {
            char pad[0x70];
            f32 stateTime;
        } view658_31;
        struct {
            char pad[0x74];
            s32 unk65C;
        } view65C_32;
        struct {
            char pad[0x78];
            s32 unk660;
        } view660_25;
        struct {
            char pad[0x78];
            s32 previousTimer;
        } view660_26;
        struct {
            char pad[0x7C];
            s32 unk664;
        } view664_27;
        struct {
            char pad[0x7C];
            s32 timer;
        } view664_28;
        struct {
            char pad[0x84];
            f32 unk66C;
        } view66C_29;
        struct {
            char pad[0x88];
            f32 unk670;
        } view670_30;
        struct {
            char pad[0x88];
            f32 shield;
        } view670_31;
        struct {
            char pad[0x90];
            f32 unk678;
        } view678_40;
        struct {
            char pad[0xA0];
            char unk688[16];
        } view688_32;
        struct {
            char pad[0xA0];
            char body[16];
        } view688_33;
        struct {
            char pad[0xA0];
            Shared_Input input;
        } view688_43;
        struct {
            char pad[0xB0];
            struct Controller * unk698;
        } view698_34;
        struct {
            char pad[0xB0];
            struct Controller * controller;
        } view698_35;
        struct {
            char pad[0xB0];
            void * controller;
        } view698_36;
        struct {
            char pad[0xB0];
            char * emitter;
        } view698_37;
        struct {
            char pad[0xB0];
            char * title;
        } view698_38;
        struct {
            char pad[0xB4];
            f32 unk69C;
        } view69C_39;
        struct {
            char pad[0xB4];
            f32 stick;
        } view69C_40;
        struct {
            char pad[0xBC];
            f32 unk6A4;
        } view6A4_41;
        struct {
            char pad[0xBC];
            f32 strafe;
        } view6A4_42;
        struct {
            char pad[0xC0];
            f32 unk6A8;
        } view6A8_43;
        struct {
            char pad[0xC0];
            f32 lift;
        } view6A8_44;
        struct {
            char pad[0xC4];
            s32 unk6AC;
        } view6AC_45;
        struct {
            char pad[0xC8];
            s32 unk6B0;
        } view6B0_46;
        struct {
            char pad[0xC8];
            s32 input;
        } view6B0_47;
        struct {
            char pad[0xC8];
            s32 state;
        } view6B0_48;
        struct {
            char pad[0xD0];
            s32 unk6B8;
        } view6B8_49;
        struct {
            char pad[0xD0];
            s32 input;
        } view6B8_50;
        struct {
            char pad[0xD8];
            f32 unk6C0;
        } view6C0_51;
        struct {
            char pad[0xD8];
            f32 climb;
        } view6C0_52;
        struct {
            char pad[0xD8];
            f32 speed;
        } view6C0_53;
        struct {
            char pad[0xD8];
            f32 velX;
        } view6C0_64;
        struct {
            char pad[0xDC];
            f32 unk6C4;
        } view6C4_54;
        struct {
            char pad[0xDC];
            f32 side;
        } view6C4_55;
        struct {
            char pad[0xDC];
            f32 velZ;
        } view6C4_67;
        struct {
            char pad[0xE0];
            f32 unk6C8;
        } view6C8_56;
        struct {
            char pad[0xE0];
            f32 speed;
        } view6C8_57;
        struct {
            char pad[0xE4];
            f32 lastVelY;
        } view6CC_70;
        struct {
            char pad[0xE8];
            s32 onGround;
        } view6D0_71;
        struct {
            char pad[0xEC];
            f32 unk6D4;
        } view6D4_58;
        struct {
            char pad[0xF0];
            f32 unk6D8;
        } view6D8_59;
        struct {
            char pad[0xF4];
            f32 unk6DC;
        } view6DC_60;
        struct {
            char pad[0xFC];
            f32 unk6E4;
        } view6E4_61;
        struct {
            char pad[0xFC];
            f32 depth;
        } view6E4_62;
        struct {
            char pad[0xFC];
            f32 airTime;
        } view6E4_77;
        struct {
            char pad[0x100];
            f32 unk6E8;
        } view6E8_63;
        struct {
            char pad[0x100];
            Vec3 unk6E8;
        } view6E8_79;
        struct {
            char pad[0x104];
            f32 unk6EC;
        } view6EC_64;
        struct {
            char pad[0x104];
            f32 height;
        } view6EC_65;
        struct {
            char pad[0x108];
            f32 unk6F0;
        } view6F0_66;
        struct {
            char pad[0x10C];
            f32 unk6F4;
        } view6F4_83;
        struct {
            char pad[0x110];
            Vec3 unk6F8;
        } view6F8_84;
        struct {
            char pad[0x11C];
            f32 unk704;
        } view704_67;
        struct {
            char pad[0x11C];
            f32 lift;
        } view704_68;
        struct {
            char pad[0x130];
            f32 unk718;
        } view718_69;
        struct {
            char pad[0x130];
            f32 crouch;
        } view718_70;
        struct {
            char pad[0x134];
            s32 unk71C;
        } view71C_89;
        struct {
            char pad[0x138];
            f32 swim;
        } view720_90;
        struct {
            char pad[0x13C];
            f32 unk724;
        } view724_71;
        struct {
            char pad[0x13C];
            f32 pitch;
        } view724_72;
        struct {
            char pad[0x140];
            f32 unk728;
        } view728_73;
        struct {
            char pad[0x140];
            f32 kickPitch;
        } view728_74;
        struct {
            char pad[0x144];
            f32 unk72C;
        } view72C_75;
        struct {
            char pad[0x144];
            f32 kickRoll;
        } view72C_76;
        struct {
            char pad[0x144];
            f32 lean;
        } view72C_77;
        struct {
            char pad[0x148];
            f32 unk730[3];
        } view730_78;
        struct {
            char pad[0x148];
            f32 sway[3];
        } view730_79;
        struct {
            char pad[0x154];
            f32 unk73C;
        } view73C_80;
        struct {
            char pad[0x154];
            f32 side;
        } view73C_81;
        struct {
            char pad[0x154];
            Vec3 weapon;
        } view73C_82;
        struct {
            char pad[0x158];
            f32 unk740;
        } view740_83;
        struct {
            char pad[0x158];
            f32 height;
        } view740_84;
        struct {
            char pad[0x15C];
            f32 unk744;
        } view744_85;
        struct {
            char pad[0x15C];
            f32 forward;
        } view744_86;
        struct {
            char pad[0x170];
            f32 unk758;
        } view758_87;
        struct {
            char pad[0x170];
            f32 bobStrength;
        } view758_88;
        struct {
            char pad[0x174];
            f32 unk75C;
        } view75C_89;
        struct {
            char pad[0x174];
            f32 bobSpeed;
        } view75C_90;
        struct {
            char pad[0x188];
            s16 unk770;
        } view770_91;
        struct {
            char pad[0x188];
            s16 nextWeapon;
        } view770_92;
        struct {
            char pad[0x188];
            s16 weapon;
        } view770_113;
        struct {
            char pad[0x18A];
            s16 pad772;
        } view772_114;
        struct {
            char pad[0x18C];
            Vec3 unk774;
        } view774_115;
        struct {
            char pad[0x198];
            f32 unk780;
        } view780_116;
        struct {
            char pad[0x19C];
            f32 unk784;
        } view784_117;
        struct {
            char pad[0x1A0];
            s32 unk788;
        } view788_93;
        struct {
            char pad[0x1A0];
            s32 icons;
        } view788_94;
        struct {
            char pad[0x1B0];
            s32 unk798;
        } view798_95;
        struct {
            char pad[0x1B0];
            s32 carried;
        } view798_96;
        struct {
            char pad[0x1B4];
            Vec3 unk79C;
        } view79C_97;
        struct {
            char pad[0x1B4];
            Vec3 carriedPosition;
        } view79C_98;
        struct {
            char pad[0x1D0];
            s32 unk7B8;
        } view7B8_99;
        struct {
            char pad[0x1D0];
            s32 target;
        } view7B8_100;
        struct {
            char pad[0x1D4];
            f32 unk7BC;
        } view7BC_101;
        struct {
            char pad[0x1D4];
            f32 timer;
        } view7BC_102;
        struct {
            char pad[0x1D8];
            Vec3 unk7C0;
        } view7C0_103;
        struct {
            char pad[0x1D8];
            Vec3 targetPosition;
        } view7C0_104;
        struct {
            char pad[0x200];
            s32 unk7E8;
        } view7E8_105;
        struct {
            char pad[0x200];
            s32 zoomed;
        } view7E8_106;
        struct {
            char pad[0x204];
            f32 unk7EC;
        } view7EC_132;
        struct {
            char pad[0x208];
            f32 unk7F0;
        } view7F0_133;
        struct {
            char pad[0x224];
            struct Mount * unk80C;
        } view80C_107;
        struct {
            char pad[0x224];
            struct Mount * mount;
        } view80C_108;
        struct {
            char pad[0x228];
            s32 unk810;
        } view810_109;
        struct {
            char pad[0x228];
            s32 kind;
        } view810_110;
        struct {
            char pad[0x22C];
            Triple unk814;
        } view814_111;
        struct {
            char pad[0x22C];
            Triple offset;
        } view814_112;
        struct {
            char pad[0x250];
            f32 unk838;
        } view838_113;
        struct {
            char pad[0x250];
            f32 rideTime;
        } view838_114;
        struct {
            char pad[0x254];
            f32 unk83C;
        } view83C_115;
        struct {
            char pad[0x254];
            f32 bump;
        } view83C_116;
        struct {
            char pad[0x258];
            s32 unk840;
        } view840_117;
        struct {
            char pad[0x258];
            s32 surfaced;
        } view840_118;
        struct {
            char pad[0x264];
            s32 unk84C;
        } view84C_149;
        struct {
            char pad[0x26C];
            f32 unk854;
        } view854_147;
        struct {
            char pad[0x274];
            s32 unk85C;
        } view85C_119;
        struct {
            char pad[0x274];
            s32 w85C;
        } view85C_120;
        struct {
            char pad[0x27C];
            s32 unk864;
        } view864_121;
        struct {
            char pad[0x27C];
            s32 f864;
        } view864_122;
        struct {
            char pad[0x280];
            s32 unk868;
        } view868_123;
        struct {
            char pad[0x280];
            s32 f868;
        } view868_124;
        struct {
            char pad[0x284];
            s32 unk86C;
        } view86C_125;
        struct {
            char pad[0x284];
            s32 parameter;
        } view86C_126;
        struct {
            char pad[0x284];
            s32 animation;
        } view86C_127;
        struct {
            char pad[0x288];
            s32 unk870;
        } view870_157;
        struct {
            char pad[0x290];
            Shared_Effect effect;
        } view878_158;
        struct {
            char pad[0x350];
            char unk938[2188];
        } view938_128;
        struct {
            char pad[0x350];
            char strokes[2188];
        } view938_129;
        struct {
            char pad[0x350];
            char strokes[2188];
        } view938_130;
        struct {
            char pad[0x350];
            s32 unk938;
        } view938_162;
        struct {
            char pad[0x6D0];
            s32 unkCB8;
        } viewCB8_163;
        struct {
            char pad[0x6E4];
            s32 unkCCC;
        } viewCCC_164;
        struct {
            char pad[0x758];
            s32 unkD40;
        } viewD40_165;
        struct {
            char pad[0x96C];
            s32 unkF54;
        } viewF54_131;
        struct {
            char pad[0x96C];
            s32 selection;
        } viewF54_132;
        struct {
            char pad[0x9A8];
            s32 unkF90;
        } viewF90_133;
        struct {
            char pad[0x9A8];
            s32 choice;
        } viewF90_134;
        struct {
            char pad[0xBCC];
            s32 unk11B4;
        } view11B4_135;
        struct {
            char pad[0xBCC];
            s32 locked;
        } view11B4_136;
        struct {
            char pad[0xBD0];
            s32 unk11B8;
        } view11B8_137;
        struct {
            char pad[0xBD0];
            s32 frozen;
        } view11B8_138;
        struct {
            char pad[0xBD4];
            s32 unk11BC;
        } view11BC_139;
        struct {
            char pad[0xBD4];
            s32 f11BC;
        } view11BC_140;
        struct {
            char pad[0xBD8];
            s32 unk11C0;
        } view11C0_141;
        struct {
            char pad[0xBD8];
            s32 f11C0;
        } view11C0_142;
        struct {
            char pad[0xBDC];
            f32 unk11C4;
        } view11C4_143;
        struct {
            char pad[0xBDC];
            f32 soundTime;
        } view11C4_144;
        struct {
            char pad[0xBE4];
            s32 unk11CC;
        } view11CC_145;
        struct {
            char pad[0xBE4];
            s32 f11CC;
        } view11CC_146;
        struct {
            char pad[0xBF0];
            f32 unk11D8;
        } view11D8_147;
        struct {
            char pad[0xBF0];
            f32 recoil;
        } view11D8_148;
        struct {
            char pad[0xBF0];
            f32 stun;
        } view11D8_149;
        struct {
            char pad[0xBF4];
            f32 unk11DC;
        } view11DC_185;
        struct {
            char pad[0xBF8];
            f32 unk11E0;
        } view11E0_186;
        struct {
            char pad[0xC00];
            s32 unk11E8;
        } view11E8_150;
        struct {
            char pad[0xC00];
            s32 f11E8;
        } view11E8_151;
        struct {
            char pad[0xC04];
            f32 unk11EC;
        } view11EC_189;
        struct {
            char pad[0xC28];
            s32 unk1210;
        } view1210_152;
        struct {
            char pad[0xC28];
            s32 marker;
        } view1210_153;
        struct {
            char pad[0xC2C];
            s32 unk1214;
        } view1214_154;
        struct {
            char pad[0xC2C];
            s32 marker;
        } view1214_155;
        struct {
            char pad[0xC2C];
            s32 markerShown;
        } view1214_156;
        struct {
            char pad[0xC30];
            s32 unk1218;
        } view1218_157;
        struct {
            char pad[0xC30];
            s32 f1218;
        } view1218_158;
        struct {
            char pad[0xC34];
            s32 unk121C;
        } view121C_159;
        struct {
            char pad[0xC34];
            s32 f121C;
        } view121C_160;
        struct {
            char pad[0xC38];
            s32 unk1220;
        } view1220_161;
        struct {
            char pad[0xC38];
            s32 f1220;
        } view1220_162;
        struct { char pad[0xE]; s16 charge; } chargeView;
        struct { char pad[0x11F4 - 0x5E8]; f32 spin; s32 frame; } rapidFireView;
    } views5E8;
    union {
        struct {
            u32 unk122C;
        } view122C_0;
        struct {
            u32 flags;
        } view122C_1;
        struct {
            s32 options;
        } view122C_2;
        struct {
            s32 f122C;
        } view122C_3;
        struct {
            s32 fxFlags;
        } view122C_4;
    } views122C;
    f32 fxTime;
    f32 fxSpeed;
    s32 fxStage;
    char pad123C[0x4];
    f32 unk1240;
    f32 unk1244;
    char pad1248[0x7C];
    union {
        struct {
            s32 unk12C4;
        } view12C4_0;
        struct {
            s32 f12C4;
        } view12C4_1;
    } views12C4;
    union {
        struct {
            s32 unk12C8;
        } view12C8_0;
        struct {
            s32 f12C8;
        } view12C8_1;
    } views12C8;
    union {
        struct {
            s32 unk12CC[8];
        } view12CC_0;
        struct {
            s32 splitsA[8];
        } view12CC_1;
    } views12CC;
    s32 unk12EC;
    char pad12F0[0x4];
    union {
        struct {
            s32 unk12F4[8];
        } view12F4_0;
        struct {
            s32 splitsB[8];
        } view12F4_1;
    } views12F4;
    char pad1314[0x20];
    union {
        struct {
            s32 unk1334;
        } view1334_0;
        struct {
            s32 f1334;
        } view1334_1;
    } views1334;
    union {
        struct {
            s32 unk1338;
        } view1338_0;
        struct {
            s32 f1338;
        } view1338_1;
    } views1338;
    union {
        struct {
            s32 unk133C;
        } view133C_0;
        struct {
            s32 laps;
        } view133C_1;
        struct {
            s32 lives;
        } view133C_2;
    } views133C;
    union {
        struct {
            s32 unk1340;
        } view1340_0;
        struct {
            s32 stalls;
        } view1340_1;
        struct {
            s32 timer;
        } view1340_2;
        struct {
            s32 respawnTimer;
        } view1340_3;
    } views1340;
    char pad1344[0x70];
    union {
        struct {
            struct StateInfo * unk13B4;
        } view13B4_0;
        struct {
            struct StateInfo * states;
        } view13B4_1;
        struct {
            struct Mode * unk13B4;
        } view13B4_2;
        struct {
            void * character;
        } view13B4_3;
        struct {
            s32 f13B4;
        } view13B4_4;
        struct {
            struct Shared_StateInfo * states;
        } view13B4_5;
    } views13B4;
    char pad13B8[0x10];
    union {
        struct {
            s32 unk13C8;
        } view13C8_0;
        struct {
            s32 w13C8;
        } view13C8_1;
        struct {
            s32 f13C8;
        } view13C8_2;
    } views13C8;
    char pad13CC[0x8];
    s32 unk13D4;
    union {
        struct {
            struct Held * unk13D8;
        } view13D8_0;
        struct {
            struct Held * held;
        } view13D8_1;
    } views13D8;
    char pad13DC[0xC];
    s32 messageIndex;
    char pad13EC[0x64];
    union {
        struct {
            s32 unk1450;
        } view1450_0;
        struct {
            s32 computer;
        } view1450_1;
        struct {
            s32 infinite;
        } view1450_2;
        struct {
            s32 unlimited;
        } view1450_3;
        struct {
            s32 uncounted;
        } view1450_4;
        struct {
            s32 f1450;
        } view1450_5;
    } views1450;
    union {
        struct {
            s32 unk1454;
        } view1454_0;
        struct {
            s32 f1454;
        } view1454_1;
    } views1454;
    char pad1458[0xC];
    union {
        struct {
            Vec3 unk1464;
        } view1464_0;
        struct {
            Vec3 aim;
        } view1464_1;
    } views1464;
    char pad1470[0x10];
    union {
        struct {
            Matrix unk1480[2];
        } view1480_0;
        struct {
            Matrix beams[2];
        } view1480_1;
    } views1480;
    union {
        struct {
            Matrix unk1500[2];
        } view1500_0;
        struct {
            Matrix lasers[2];
        } view1500_1;
    } views1500;
    union {
        struct {
            Matrix unk1580[2];
        } view1580_0;
        struct {
            Matrix dots[2];
        } view1580_1;
    } views1580;
    char pad1600[0xD4];
    union {
        struct {
            s32 unk16D4;
        } view16D4_0;
        struct {
            s32 f16D4;
        } view16D4_1;
    } views16D4;
    u16 unk16D8;
    char pad16DA[0x6];
    union {
        struct {
            struct SharedPlayer_func_80408C4C_de * unk16E0;
        } view16E0_0;
        struct {
            struct SharedPlayer_func_80408C4C_de * next;
        } view16E0_1;
        struct {
            struct SharedPlayer_func_80408C4C_de * next;
        } view16E0_2;
    } views16E0;
};

/* unbake evidence input: c3RydWN0IEJvZHk7CnN0cnVjdCBDaGFyYWN0ZXI7CnN0cnVjdCBDb250cm9sbGVyOwpzdHJ1Y3QgQ29udHJvbHM7CnN0cnVjdCBDdHJsOwpzdHJ1Y3QgSGVsZDsKc3RydWN0IE1vZGU7CnN0cnVjdCBNb2RlbDsKc3RydWN0IE1vdW50OwpzdHJ1Y3QgUHJvZmlsZV9mdW5jXzgwNDA4QzRDX2RlOwpzdHJ1Y3QgUmVjb3JkOwpzdHJ1Y3QgUmlkZXI7CnN0cnVjdCBTZXR0aW5nczsKc3RydWN0IFNoYXJlZFBsYXllcl9mdW5jXzgwNDA4QzRDX2RlOwpzdHJ1Y3QgU2hhcmVkX0JvZHk7CnN0cnVjdCBTaGFyZWRfSHVkOwpzdHJ1Y3QgU2hhcmVkX01vZGVsOwpzdHJ1Y3QgU2hhcmVkX1Byb2ZpbGU7CnN0cnVjdCBTaGFyZWRfU3RhdGVJbmZvOwpzdHJ1Y3QgU2hhcmVkX1ZvaWNlOwpzdHJ1Y3QgU3RhdGVJbmZvOwpzdHJ1Y3QgVGVhbUluZm87CnN0cnVjdCBWaWV3OwpzdHJ1Y3QgU2hhcmVkUGxheWVyX2Z1bmNfODA0MDhDNENfZGUgewogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHU4IHVuazBbMjRdOwogICAgICAgIH0gdmlldzBfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICB1OCBwYWQwWzI0XTsKICAgICAgICB9IHZpZXcwXzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgzXTsKICAgICAgICAgICAgdTggdGVhbTsKICAgICAgICB9IHZpZXczXzI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg4XTsKICAgICAgICAgICAgVmVjMyB1bms4OwogICAgICAgIH0gdmlldzhfMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDhdOwogICAgICAgICAgICBWZWMzIHBvczsKICAgICAgICB9IHZpZXc4XzM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg4XTsKICAgICAgICAgICAgVmVjMyBwb3NpdGlvbjsKICAgICAgICB9IHZpZXc4XzQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNF07CiAgICAgICAgICAgIHN0cnVjdCBTaGFyZWRfTW9kZWwgKiBtb2RlbDsKICAgICAgICB9IHZpZXcxNF82OwogICAgICAgIHN0cnVjdCB7IGNoYXIgcGFkWzhdOyBzMzIgcG9zaXRpb25Xb3Jkc1szXTsgfSBwb3NpdGlvbkJpdHM7CiAgICB9IHZpZXdzMDsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyICogdW5rMTg7CiAgICAgICAgfSB2aWV3MThfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyICogdHJhY2s7CiAgICAgICAgfSB2aWV3MThfMTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzdHJ1Y3QgTW9kZWwgKiBtb2RlbDsKICAgICAgICB9IHZpZXcxOF8yOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHN0cnVjdCBCb2R5ICogYm9keTsKICAgICAgICB9IHZpZXcxOF8zOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHN0cnVjdCBDaGFyYWN0ZXIgKiBjaGFyYWN0ZXI7CiAgICAgICAgfSB2aWV3MThfNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzdHJ1Y3QgU2hhcmVkX0JvZHkgKiBib2R5OwogICAgICAgIH0gdmlldzE4XzU7CiAgICB9IHZpZXdzMTg7CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgdTggdW5rMUNbMzQ0XTsKICAgICAgICB9IHZpZXcxQ18wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHU4IHBhZDFbMzQ0XTsKICAgICAgICB9IHZpZXcxQ18xOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NF07CiAgICAgICAgICAgIGYzMiB2ZWxZOwogICAgICAgIH0gdmlldzIwXzI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQ107CiAgICAgICAgICAgIHMzMiB1bmszODsKICAgICAgICB9IHZpZXczOF8yOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MUNdOwogICAgICAgICAgICBzMzIgZmxhZ3M7CiAgICAgICAgfSB2aWV3MzhfMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI0XTsKICAgICAgICAgICAgZjMyIHVuazQwOwogICAgICAgIH0gdmlldzQwXzU7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg0MF07CiAgICAgICAgICAgIFNoYXJlZF9RdWFkIHVuazVDOwogICAgICAgIH0gdmlldzVDXzY7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg1MF07CiAgICAgICAgICAgIGYzMiB1bms2QzsKICAgICAgICB9IHZpZXc2Q180OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NTBdOwogICAgICAgICAgICBmMzIgaGVhZGluZzsKICAgICAgICB9IHZpZXc2Q181OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NTBdOwogICAgICAgICAgICBmMzIgeWF3OwogICAgICAgIH0gdmlldzZDXzk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDOF07CiAgICAgICAgICAgIHUxNiB1bmtFNDsKICAgICAgICB9IHZpZXdFNF82OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QzhdOwogICAgICAgICAgICB1MTYga2luZDsKICAgICAgICB9IHZpZXdFNF83OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RTRdOwogICAgICAgICAgICBzMzIgdW5rMTAwOwogICAgICAgIH0gdmlldzEwMF84OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RTRdOwogICAgICAgICAgICBzMzIgZmxhZ3M7CiAgICAgICAgfSB2aWV3MTAwXzk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhFOF07CiAgICAgICAgICAgIGYzMiB1bmsxMDQ7CiAgICAgICAgfSB2aWV3MTA0XzEwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RThdOwogICAgICAgICAgICBmMzIgaWRsZVRpbWU7CiAgICAgICAgfSB2aWV3MTA0XzExOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RUNdOwogICAgICAgICAgICBzMTYgYW5pbTsKICAgICAgICB9IHZpZXcxMDhfMTY7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhGMl07CiAgICAgICAgICAgIHM4IHVuazEwRTsKICAgICAgICB9IHZpZXcxMEVfMTI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhGMl07CiAgICAgICAgICAgIHM4IGlkbGU7CiAgICAgICAgfSB2aWV3MTBFXzEzOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RjJdOwogICAgICAgICAgICBzOCByZXBsYXlpbmc7CiAgICAgICAgfSB2aWV3MTBFXzE0OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RjJdOwogICAgICAgICAgICBzOCBhbmltUGVuZGluZzsKICAgICAgICB9IHZpZXcxMEVfMjA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNTRdOwogICAgICAgICAgICBjaGFyIHVuazE3MFsxMDBdOwogICAgICAgIH0gdmlldzE3MF8xNTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDE1NF07CiAgICAgICAgICAgIGNoYXIgYm9keVsxMDBdOwogICAgICAgIH0gdmlldzE3MF8xNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDE1NF07CiAgICAgICAgICAgIHMzMiB1bmsxNzA7CiAgICAgICAgfSB2aWV3MTcwXzIzOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTU4XTsKICAgICAgICAgICAgczMyIHVuazE3NDsKICAgICAgICB9IHZpZXcxNzRfMTc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNUNdOwogICAgICAgICAgICB1OCB1bmsxNzhbNzQwXTsKICAgICAgICB9IHZpZXcxNzhfMTg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNUNdOwogICAgICAgICAgICB1OCBwYWQyWzc0MF07CiAgICAgICAgfSB2aWV3MTc4XzE5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MUI4XTsKICAgICAgICAgICAgZjMyIHVuazFENDsKICAgICAgICB9IHZpZXcxRDRfMjA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQjhdOwogICAgICAgICAgICBmMzIgaG9sZFRpbWU7CiAgICAgICAgfSB2aWV3MUQ0XzIxOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MUJDXTsKICAgICAgICAgICAgc3RydWN0IFNoYXJlZFBsYXllcl9mdW5jXzgwNDA4QzRDX2RlICogdW5rMUQ4OwogICAgICAgIH0gdmlldzFEOF8yMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDFCQ107CiAgICAgICAgICAgIHN0cnVjdCBTaGFyZWRQbGF5ZXJfZnVuY184MDQwOEM0Q19kZSAqIHNlbGY7CiAgICAgICAgfSB2aWV3MUQ4XzIzOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MUJDXTsKICAgICAgICAgICAgc3RydWN0IFNoYXJlZFBsYXllcl9mdW5jXzgwNDA4QzRDX2RlICogZjFEODsKICAgICAgICB9IHZpZXcxRDhfMjQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQkNdOwogICAgICAgICAgICB2b2lkICogdW5rMUQ4OwogICAgICAgIH0gdmlldzFEOF8zMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI0NF07CiAgICAgICAgICAgIFZlYzMgdW5rMjYwOwogICAgICAgIH0gdmlldzI2MF8yNTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI0NF07CiAgICAgICAgICAgIFZlYzMgbXV6emxlOwogICAgICAgIH0gdmlldzI2MF8yNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDJDQ107CiAgICAgICAgICAgIGNoYXIgdW5rMkU4WzM2OF07CiAgICAgICAgfSB2aWV3MkU4XzI3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MkNDXTsKICAgICAgICAgICAgY2hhciB3ZWFwb25bMzY4XTsKICAgICAgICB9IHZpZXcyRThfMjg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyQ0NdOwogICAgICAgICAgICBTaGFyZWRfRW1pdHRlciBlbWl0dGVyOwogICAgICAgIH0gdmlldzJFOF8zNzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDQzQ107CiAgICAgICAgICAgIGNoYXIgdW5rNDU4WzM4NF07CiAgICAgICAgfSB2aWV3NDU4XzI5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NDNDXTsKICAgICAgICAgICAgY2hhciBhbW1vWzM4NF07CiAgICAgICAgfSB2aWV3NDU4XzMwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NDNDXTsKICAgICAgICAgICAgczMyIHVuazQ1ODsKICAgICAgICB9IHZpZXc0NThfNDA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg0NDBdOwogICAgICAgICAgICBzMzIgdW5rNDVDOwogICAgICAgIH0gdmlldzQ1Q18zMTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDQ0NF07CiAgICAgICAgICAgIHU4IHVuazQ2MFszNzZdOwogICAgICAgIH0gdmlldzQ2MF8zMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDQ0NF07CiAgICAgICAgICAgIHU4IHBhZDNbMzc2XTsKICAgICAgICB9IHZpZXc0NjBfMzM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg0NjhdOwogICAgICAgICAgICBzdHJ1Y3QgU2hhcmVkX1ZvaWNlICogdm9pY2U7CiAgICAgICAgfSB2aWV3NDg0XzQ0OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NDcwXTsKICAgICAgICAgICAgczggdW5rNDhDOwogICAgICAgIH0gdmlldzQ4Q18zNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDQ3MF07CiAgICAgICAgICAgIHM4IHN0YXRlOwogICAgICAgIH0gdmlldzQ4Q18zNTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDRBNF07CiAgICAgICAgICAgIHZvaWQgKiB1bms0QzA7CiAgICAgICAgfSB2aWV3NEMwXzQ3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NTA3XTsKICAgICAgICAgICAgczggdW5rNTIzOwogICAgICAgIH0gdmlldzUyM18zNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDUwN107CiAgICAgICAgICAgIHM4IGJ1c3k7CiAgICAgICAgfSB2aWV3NTIzXzM3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NTc4XTsKICAgICAgICAgICAgczMyIHVuazU5NDsKICAgICAgICB9IHZpZXc1OTRfMzg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg1NzhdOwogICAgICAgICAgICBzMzIgZ2VhcjsKICAgICAgICB9IHZpZXc1OTRfMzk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg1NzhdOwogICAgICAgICAgICBzMzIgbW9kZTsKICAgICAgICB9IHZpZXc1OTRfNDA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg1ODRdOwogICAgICAgICAgICBmMzIgdW5rNUEwOwogICAgICAgIH0gdmlldzVBMF80MTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDU4NF07CiAgICAgICAgICAgIGYzMiBjaGFyZ2U7CiAgICAgICAgfSB2aWV3NUEwXzQyOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NUI0XTsKICAgICAgICAgICAgczMyIHVuazVEMDsKICAgICAgICB9IHZpZXc1RDBfNDM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg1QjRdOwogICAgICAgICAgICBzMzIgZjVEMDsKICAgICAgICB9IHZpZXc1RDBfNDQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg1QjhdOwogICAgICAgICAgICBzMzIgdW5rNUQ0OwogICAgICAgIH0gdmlldzVENF80NTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDVCOF07CiAgICAgICAgICAgIHMzMiBzbG90OwogICAgICAgIH0gdmlldzVENF80NjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDVCOF07CiAgICAgICAgICAgIHMzMiBwcm9maWxlOwogICAgICAgIH0gdmlldzVENF80NzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDVCOF07CiAgICAgICAgICAgIHMzMiBmNUQ0OwogICAgICAgIH0gdmlldzVENF80ODsKICAgIH0gdmlld3MxQzsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzdHJ1Y3QgUmVjb3JkICogdW5rNUQ4OwogICAgICAgIH0gdmlldzVEOF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHN0cnVjdCBSZWNvcmQgKiByZWNvcmQ7CiAgICAgICAgfSB2aWV3NUQ4XzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IENvbnRyb2xzICogY29udHJvbHM7CiAgICAgICAgfSB2aWV3NUQ4XzI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IFRlYW1JbmZvICogdGVhbUluZm87CiAgICAgICAgfSB2aWV3NUQ4XzM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IEN0cmwgKiBjdHJsOwogICAgICAgIH0gdmlldzVEOF80OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHVuc2lnbmVkIGNoYXIgKiBpbmZvOwogICAgICAgIH0gdmlldzVEOF81OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHN0cnVjdCBQcm9maWxlX2Z1bmNfODA0MDhDNENfZGUgKiBwcm9maWxlOwogICAgICAgIH0gdmlldzVEOF82OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHN0cnVjdCBTZXR0aW5ncyAqIHNldHRpbmdzOwogICAgICAgIH0gdmlldzVEOF83OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBmNUQ4OwogICAgICAgIH0gdmlldzVEOF84OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHN0cnVjdCBTaGFyZWRfUHJvZmlsZSAqIHByb2ZpbGU7CiAgICAgICAgfSB2aWV3NUQ4Xzk7CiAgICB9IHZpZXdzNUQ4OwogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHZvaWQgKiB1bms1REM7CiAgICAgICAgfSB2aWV3NURDXzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgdm9pZCAqIHZpZXc7CiAgICAgICAgfSB2aWV3NURDXzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IFZpZXcgKiB2aWV3OwogICAgICAgIH0gdmlldzVEQ18yOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHU4IHBhZDRbOF07CiAgICAgICAgfSB2aWV3NURDXzM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgdm9pZCAqIGVudGl0eTsKICAgICAgICB9IHZpZXc1RENfNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzdHJ1Y3QgUmlkZXIgKiByaWRlcjsKICAgICAgICB9IHZpZXc1RENfNTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyICogc3RvcmFnZTsKICAgICAgICB9IHZpZXc1RENfNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyICogbWVzc2FnZXM7CiAgICAgICAgfSB2aWV3NURDXzc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IFNoYXJlZF9IdWQgKiBodWQ7CiAgICAgICAgfSB2aWV3NURDXzg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg0XTsKICAgICAgICAgICAgczMyIHVuazVFMDsKICAgICAgICB9IHZpZXc1RTBfODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDRdOwogICAgICAgICAgICBzMzIgc3RhdGU7CiAgICAgICAgfSB2aWV3NUUwXzk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg0XTsKICAgICAgICAgICAgczMyIHNsb3Q7CiAgICAgICAgfSB2aWV3NUUwXzEwOwogICAgfSB2aWV3czVEQzsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgdW5rNUU0OwogICAgICAgIH0gdmlldzVFNF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBhY3RpdmU7CiAgICAgICAgfSB2aWV3NUU0XzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIGhlYWx0aDsKICAgICAgICB9IHZpZXc1RTRfMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgYWxpdmU7CiAgICAgICAgfSB2aWV3NUU0XzM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIGhvbGRpbmc7CiAgICAgICAgfSB2aWV3NUU0XzQ7CiAgICB9IHZpZXdzNUU0OwogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHU4IHVuazVFOFszMTQwXTsKICAgICAgICB9IHZpZXc1RThfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICB1OCBwYWQ1WzMxNDBdOwogICAgICAgIH0gdmlldzVFOF8xOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4Ml07CiAgICAgICAgICAgIHMxNiB1bms1RUE7CiAgICAgICAgfSB2aWV3NUVBXzI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyXTsKICAgICAgICAgICAgczE2IHJlc3Bhd25zOwogICAgICAgIH0gdmlldzVFQV8zOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4Ml07CiAgICAgICAgICAgIHMxNiBydW5UeXBlOwogICAgICAgIH0gdmlldzVFQV80OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NF07CiAgICAgICAgICAgIHMzMiB1bms1RUM7CiAgICAgICAgfSB2aWV3NUVDXzU7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg0XTsKICAgICAgICAgICAgczMyIG1vZGVsOwogICAgICAgIH0gdmlldzVFQ182OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NF07CiAgICAgICAgICAgIHMzMiBzcGF3blBvaW50OwogICAgICAgIH0gdmlldzVFQ183OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NF07CiAgICAgICAgICAgIHMzMiBmNUVDOwogICAgICAgIH0gdmlldzVFQ184OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4OF07CiAgICAgICAgICAgIHMzMiB1bms1RjA7CiAgICAgICAgfSB2aWV3NUYwXzk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg4XTsKICAgICAgICAgICAgczMyIGY1RjA7CiAgICAgICAgfSB2aWV3NUYwXzEwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4Q107CiAgICAgICAgICAgIHMxNiB1bms1RjRbNF07CiAgICAgICAgfSB2aWV3NUY0XzExOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4Q107CiAgICAgICAgICAgIHMxNiBhbW1vWzRdOwogICAgICAgIH0gdmlldzVGNF8xMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweENdOwogICAgICAgICAgICBzMTYgYW1tb1szXTsKICAgICAgICB9IHZpZXc1RjRfMTM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQV07CiAgICAgICAgICAgIFNoYXJlZF9TbG90IHNsb3RzWzIyXTsKICAgICAgICB9IHZpZXc2MDJfMTQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg0Nl07CiAgICAgICAgICAgIHMxNiB1bms2MkU7CiAgICAgICAgfSB2aWV3NjJFXzEzOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NDZdOwogICAgICAgICAgICBzMTYgd2VhcG9uOwogICAgICAgIH0gdmlldzYyRV8xNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDQ2XTsKICAgICAgICAgICAgczE2IGNoYXJhY3RlcjsKICAgICAgICB9IHZpZXc2MkVfMTc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg2OF07CiAgICAgICAgICAgIHMxNiB1bms2NTA7CiAgICAgICAgfSB2aWV3NjUwXzE1OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NjhdOwogICAgICAgICAgICBzMTYgc3RhdGU7CiAgICAgICAgfSB2aWV3NjUwXzE2OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NjhdOwogICAgICAgICAgICBzMTYgYWN0aW9uOwogICAgICAgIH0gdmlldzY1MF8xNzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDY4XTsKICAgICAgICAgICAgczE2IG1vZGU7CiAgICAgICAgfSB2aWV3NjUwXzE4OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NkFdOwogICAgICAgICAgICBzMTYgdW5rNjUyOwogICAgICAgIH0gdmlldzY1Ml8xOTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDZBXTsKICAgICAgICAgICAgczE2IHByZXZpb3VzOwogICAgICAgIH0gdmlldzY1Ml8yMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDZBXTsKICAgICAgICAgICAgczE2IHBhZDY1MjsKICAgICAgICB9IHZpZXc2NTJfMjQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg2Q107CiAgICAgICAgICAgIHMxNiBwcmV2U3RhdGU7CiAgICAgICAgfSB2aWV3NjU0XzI1OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NkVdOwogICAgICAgICAgICBzMTYgcGFkNjU2OwogICAgICAgIH0gdmlldzY1Nl8yNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDcwXTsKICAgICAgICAgICAgZjMyIHVuazY1ODsKICAgICAgICB9IHZpZXc2NThfMjE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg3MF07CiAgICAgICAgICAgIGYzMiBjb3VudGVyOwogICAgICAgIH0gdmlldzY1OF8yMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDcwXTsKICAgICAgICAgICAgZjMyIHN0cmlkZTsKICAgICAgICB9IHZpZXc2NThfMjM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg3MF07CiAgICAgICAgICAgIGYzMiBzd2ltVGltZTsKICAgICAgICB9IHZpZXc2NThfMjQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg3MF07CiAgICAgICAgICAgIGYzMiBzdGF0ZVRpbWU7CiAgICAgICAgfSB2aWV3NjU4XzMxOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4NzRdOwogICAgICAgICAgICBzMzIgdW5rNjVDOwogICAgICAgIH0gdmlldzY1Q18zMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDc4XTsKICAgICAgICAgICAgczMyIHVuazY2MDsKICAgICAgICB9IHZpZXc2NjBfMjU7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg3OF07CiAgICAgICAgICAgIHMzMiBwcmV2aW91c1RpbWVyOwogICAgICAgIH0gdmlldzY2MF8yNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDdDXTsKICAgICAgICAgICAgczMyIHVuazY2NDsKICAgICAgICB9IHZpZXc2NjRfMjc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg3Q107CiAgICAgICAgICAgIHMzMiB0aW1lcjsKICAgICAgICB9IHZpZXc2NjRfMjg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg4NF07CiAgICAgICAgICAgIGYzMiB1bms2NkM7CiAgICAgICAgfSB2aWV3NjZDXzI5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4ODhdOwogICAgICAgICAgICBmMzIgdW5rNjcwOwogICAgICAgIH0gdmlldzY3MF8zMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDg4XTsKICAgICAgICAgICAgZjMyIHNoaWVsZDsKICAgICAgICB9IHZpZXc2NzBfMzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHg5MF07CiAgICAgICAgICAgIGYzMiB1bms2Nzg7CiAgICAgICAgfSB2aWV3Njc4XzQwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QTBdOwogICAgICAgICAgICBjaGFyIHVuazY4OFsxNl07CiAgICAgICAgfSB2aWV3Njg4XzMyOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QTBdOwogICAgICAgICAgICBjaGFyIGJvZHlbMTZdOwogICAgICAgIH0gdmlldzY4OF8zMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEEwXTsKICAgICAgICAgICAgU2hhcmVkX0lucHV0IGlucHV0OwogICAgICAgIH0gdmlldzY4OF80MzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEIwXTsKICAgICAgICAgICAgc3RydWN0IENvbnRyb2xsZXIgKiB1bms2OTg7CiAgICAgICAgfSB2aWV3Njk4XzM0OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QjBdOwogICAgICAgICAgICBzdHJ1Y3QgQ29udHJvbGxlciAqIGNvbnRyb2xsZXI7CiAgICAgICAgfSB2aWV3Njk4XzM1OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QjBdOwogICAgICAgICAgICB2b2lkICogY29udHJvbGxlcjsKICAgICAgICB9IHZpZXc2OThfMzY7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhCMF07CiAgICAgICAgICAgIGNoYXIgKiBlbWl0dGVyOwogICAgICAgIH0gdmlldzY5OF8zNzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEIwXTsKICAgICAgICAgICAgY2hhciAqIHRpdGxlOwogICAgICAgIH0gdmlldzY5OF8zODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEI0XTsKICAgICAgICAgICAgZjMyIHVuazY5QzsKICAgICAgICB9IHZpZXc2OUNfMzk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhCNF07CiAgICAgICAgICAgIGYzMiBzdGljazsKICAgICAgICB9IHZpZXc2OUNfNDA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhCQ107CiAgICAgICAgICAgIGYzMiB1bms2QTQ7CiAgICAgICAgfSB2aWV3NkE0XzQxOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QkNdOwogICAgICAgICAgICBmMzIgc3RyYWZlOwogICAgICAgIH0gdmlldzZBNF80MjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEMwXTsKICAgICAgICAgICAgZjMyIHVuazZBODsKICAgICAgICB9IHZpZXc2QThfNDM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDMF07CiAgICAgICAgICAgIGYzMiBsaWZ0OwogICAgICAgIH0gdmlldzZBOF80NDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEM0XTsKICAgICAgICAgICAgczMyIHVuazZBQzsKICAgICAgICB9IHZpZXc2QUNfNDU7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDOF07CiAgICAgICAgICAgIHMzMiB1bms2QjA7CiAgICAgICAgfSB2aWV3NkIwXzQ2OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QzhdOwogICAgICAgICAgICBzMzIgaW5wdXQ7CiAgICAgICAgfSB2aWV3NkIwXzQ3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QzhdOwogICAgICAgICAgICBzMzIgc3RhdGU7CiAgICAgICAgfSB2aWV3NkIwXzQ4OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RDBdOwogICAgICAgICAgICBzMzIgdW5rNkI4OwogICAgICAgIH0gdmlldzZCOF80OTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEQwXTsKICAgICAgICAgICAgczMyIGlucHV0OwogICAgICAgIH0gdmlldzZCOF81MDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEQ4XTsKICAgICAgICAgICAgZjMyIHVuazZDMDsKICAgICAgICB9IHZpZXc2QzBfNTE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhEOF07CiAgICAgICAgICAgIGYzMiBjbGltYjsKICAgICAgICB9IHZpZXc2QzBfNTI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhEOF07CiAgICAgICAgICAgIGYzMiBzcGVlZDsKICAgICAgICB9IHZpZXc2QzBfNTM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhEOF07CiAgICAgICAgICAgIGYzMiB2ZWxYOwogICAgICAgIH0gdmlldzZDMF82NDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweERDXTsKICAgICAgICAgICAgZjMyIHVuazZDNDsKICAgICAgICB9IHZpZXc2QzRfNTQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhEQ107CiAgICAgICAgICAgIGYzMiBzaWRlOwogICAgICAgIH0gdmlldzZDNF81NTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweERDXTsKICAgICAgICAgICAgZjMyIHZlbFo7CiAgICAgICAgfSB2aWV3NkM0XzY3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RTBdOwogICAgICAgICAgICBmMzIgdW5rNkM4OwogICAgICAgIH0gdmlldzZDOF81NjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEUwXTsKICAgICAgICAgICAgZjMyIHNwZWVkOwogICAgICAgIH0gdmlldzZDOF81NzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEU0XTsKICAgICAgICAgICAgZjMyIGxhc3RWZWxZOwogICAgICAgIH0gdmlldzZDQ183MDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEU4XTsKICAgICAgICAgICAgczMyIG9uR3JvdW5kOwogICAgICAgIH0gdmlldzZEMF83MTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEVDXTsKICAgICAgICAgICAgZjMyIHVuazZENDsKICAgICAgICB9IHZpZXc2RDRfNTg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhGMF07CiAgICAgICAgICAgIGYzMiB1bms2RDg7CiAgICAgICAgfSB2aWV3NkQ4XzU5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4RjRdOwogICAgICAgICAgICBmMzIgdW5rNkRDOwogICAgICAgIH0gdmlldzZEQ182MDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEZDXTsKICAgICAgICAgICAgZjMyIHVuazZFNDsKICAgICAgICB9IHZpZXc2RTRfNjE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhGQ107CiAgICAgICAgICAgIGYzMiBkZXB0aDsKICAgICAgICB9IHZpZXc2RTRfNjI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhGQ107CiAgICAgICAgICAgIGYzMiBhaXJUaW1lOwogICAgICAgIH0gdmlldzZFNF83NzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDEwMF07CiAgICAgICAgICAgIGYzMiB1bms2RTg7CiAgICAgICAgfSB2aWV3NkU4XzYzOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTAwXTsKICAgICAgICAgICAgVmVjMyB1bms2RTg7CiAgICAgICAgfSB2aWV3NkU4Xzc5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTA0XTsKICAgICAgICAgICAgZjMyIHVuazZFQzsKICAgICAgICB9IHZpZXc2RUNfNjQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxMDRdOwogICAgICAgICAgICBmMzIgaGVpZ2h0OwogICAgICAgIH0gdmlldzZFQ182NTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDEwOF07CiAgICAgICAgICAgIGYzMiB1bms2RjA7CiAgICAgICAgfSB2aWV3NkYwXzY2OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTBDXTsKICAgICAgICAgICAgZjMyIHVuazZGNDsKICAgICAgICB9IHZpZXc2RjRfODM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxMTBdOwogICAgICAgICAgICBWZWMzIHVuazZGODsKICAgICAgICB9IHZpZXc2RjhfODQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxMUNdOwogICAgICAgICAgICBmMzIgdW5rNzA0OwogICAgICAgIH0gdmlldzcwNF82NzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDExQ107CiAgICAgICAgICAgIGYzMiBsaWZ0OwogICAgICAgIH0gdmlldzcwNF82ODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDEzMF07CiAgICAgICAgICAgIGYzMiB1bms3MTg7CiAgICAgICAgfSB2aWV3NzE4XzY5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTMwXTsKICAgICAgICAgICAgZjMyIGNyb3VjaDsKICAgICAgICB9IHZpZXc3MThfNzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxMzRdOwogICAgICAgICAgICBzMzIgdW5rNzFDOwogICAgICAgIH0gdmlldzcxQ184OTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDEzOF07CiAgICAgICAgICAgIGYzMiBzd2ltOwogICAgICAgIH0gdmlldzcyMF85MDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDEzQ107CiAgICAgICAgICAgIGYzMiB1bms3MjQ7CiAgICAgICAgfSB2aWV3NzI0XzcxOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTNDXTsKICAgICAgICAgICAgZjMyIHBpdGNoOwogICAgICAgIH0gdmlldzcyNF83MjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDE0MF07CiAgICAgICAgICAgIGYzMiB1bms3Mjg7CiAgICAgICAgfSB2aWV3NzI4XzczOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTQwXTsKICAgICAgICAgICAgZjMyIGtpY2tQaXRjaDsKICAgICAgICB9IHZpZXc3MjhfNzQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNDRdOwogICAgICAgICAgICBmMzIgdW5rNzJDOwogICAgICAgIH0gdmlldzcyQ183NTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDE0NF07CiAgICAgICAgICAgIGYzMiBraWNrUm9sbDsKICAgICAgICB9IHZpZXc3MkNfNzY7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNDRdOwogICAgICAgICAgICBmMzIgbGVhbjsKICAgICAgICB9IHZpZXc3MkNfNzc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNDhdOwogICAgICAgICAgICBmMzIgdW5rNzMwWzNdOwogICAgICAgIH0gdmlldzczMF83ODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDE0OF07CiAgICAgICAgICAgIGYzMiBzd2F5WzNdOwogICAgICAgIH0gdmlldzczMF83OTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDE1NF07CiAgICAgICAgICAgIGYzMiB1bms3M0M7CiAgICAgICAgfSB2aWV3NzNDXzgwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTU0XTsKICAgICAgICAgICAgZjMyIHNpZGU7CiAgICAgICAgfSB2aWV3NzNDXzgxOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTU0XTsKICAgICAgICAgICAgVmVjMyB3ZWFwb247CiAgICAgICAgfSB2aWV3NzNDXzgyOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTU4XTsKICAgICAgICAgICAgZjMyIHVuazc0MDsKICAgICAgICB9IHZpZXc3NDBfODM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNThdOwogICAgICAgICAgICBmMzIgaGVpZ2h0OwogICAgICAgIH0gdmlldzc0MF84NDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDE1Q107CiAgICAgICAgICAgIGYzMiB1bms3NDQ7CiAgICAgICAgfSB2aWV3NzQ0Xzg1OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTVDXTsKICAgICAgICAgICAgZjMyIGZvcndhcmQ7CiAgICAgICAgfSB2aWV3NzQ0Xzg2OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTcwXTsKICAgICAgICAgICAgZjMyIHVuazc1ODsKICAgICAgICB9IHZpZXc3NThfODc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNzBdOwogICAgICAgICAgICBmMzIgYm9iU3RyZW5ndGg7CiAgICAgICAgfSB2aWV3NzU4Xzg4OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTc0XTsKICAgICAgICAgICAgZjMyIHVuazc1QzsKICAgICAgICB9IHZpZXc3NUNfODk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxNzRdOwogICAgICAgICAgICBmMzIgYm9iU3BlZWQ7CiAgICAgICAgfSB2aWV3NzVDXzkwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTg4XTsKICAgICAgICAgICAgczE2IHVuazc3MDsKICAgICAgICB9IHZpZXc3NzBfOTE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxODhdOwogICAgICAgICAgICBzMTYgbmV4dFdlYXBvbjsKICAgICAgICB9IHZpZXc3NzBfOTI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxODhdOwogICAgICAgICAgICBzMTYgd2VhcG9uOwogICAgICAgIH0gdmlldzc3MF8xMTM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxOEFdOwogICAgICAgICAgICBzMTYgcGFkNzcyOwogICAgICAgIH0gdmlldzc3Ml8xMTQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxOENdOwogICAgICAgICAgICBWZWMzIHVuazc3NDsKICAgICAgICB9IHZpZXc3NzRfMTE1OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTk4XTsKICAgICAgICAgICAgZjMyIHVuazc4MDsKICAgICAgICB9IHZpZXc3ODBfMTE2OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MTlDXTsKICAgICAgICAgICAgZjMyIHVuazc4NDsKICAgICAgICB9IHZpZXc3ODRfMTE3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MUEwXTsKICAgICAgICAgICAgczMyIHVuazc4ODsKICAgICAgICB9IHZpZXc3ODhfOTM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQTBdOwogICAgICAgICAgICBzMzIgaWNvbnM7CiAgICAgICAgfSB2aWV3Nzg4Xzk0OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MUIwXTsKICAgICAgICAgICAgczMyIHVuazc5ODsKICAgICAgICB9IHZpZXc3OThfOTU7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQjBdOwogICAgICAgICAgICBzMzIgY2FycmllZDsKICAgICAgICB9IHZpZXc3OThfOTY7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQjRdOwogICAgICAgICAgICBWZWMzIHVuazc5QzsKICAgICAgICB9IHZpZXc3OUNfOTc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxQjRdOwogICAgICAgICAgICBWZWMzIGNhcnJpZWRQb3NpdGlvbjsKICAgICAgICB9IHZpZXc3OUNfOTg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgxRDBdOwogICAgICAgICAgICBzMzIgdW5rN0I4OwogICAgICAgIH0gdmlldzdCOF85OTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDFEMF07CiAgICAgICAgICAgIHMzMiB0YXJnZXQ7CiAgICAgICAgfSB2aWV3N0I4XzEwMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDFENF07CiAgICAgICAgICAgIGYzMiB1bms3QkM7CiAgICAgICAgfSB2aWV3N0JDXzEwMTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDFENF07CiAgICAgICAgICAgIGYzMiB0aW1lcjsKICAgICAgICB9IHZpZXc3QkNfMTAyOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MUQ4XTsKICAgICAgICAgICAgVmVjMyB1bms3QzA7CiAgICAgICAgfSB2aWV3N0MwXzEwMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDFEOF07CiAgICAgICAgICAgIFZlYzMgdGFyZ2V0UG9zaXRpb247CiAgICAgICAgfSB2aWV3N0MwXzEwNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDIwMF07CiAgICAgICAgICAgIHMzMiB1bms3RTg7CiAgICAgICAgfSB2aWV3N0U4XzEwNTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDIwMF07CiAgICAgICAgICAgIHMzMiB6b29tZWQ7CiAgICAgICAgfSB2aWV3N0U4XzEwNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDIwNF07CiAgICAgICAgICAgIGYzMiB1bms3RUM7CiAgICAgICAgfSB2aWV3N0VDXzEzMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDIwOF07CiAgICAgICAgICAgIGYzMiB1bms3RjA7CiAgICAgICAgfSB2aWV3N0YwXzEzMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDIyNF07CiAgICAgICAgICAgIHN0cnVjdCBNb3VudCAqIHVuazgwQzsKICAgICAgICB9IHZpZXc4MENfMTA3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MjI0XTsKICAgICAgICAgICAgc3RydWN0IE1vdW50ICogbW91bnQ7CiAgICAgICAgfSB2aWV3ODBDXzEwODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDIyOF07CiAgICAgICAgICAgIHMzMiB1bms4MTA7CiAgICAgICAgfSB2aWV3ODEwXzEwOTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDIyOF07CiAgICAgICAgICAgIHMzMiBraW5kOwogICAgICAgIH0gdmlldzgxMF8xMTA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyMkNdOwogICAgICAgICAgICBUcmlwbGUgdW5rODE0OwogICAgICAgIH0gdmlldzgxNF8xMTE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyMkNdOwogICAgICAgICAgICBUcmlwbGUgb2Zmc2V0OwogICAgICAgIH0gdmlldzgxNF8xMTI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyNTBdOwogICAgICAgICAgICBmMzIgdW5rODM4OwogICAgICAgIH0gdmlldzgzOF8xMTM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyNTBdOwogICAgICAgICAgICBmMzIgcmlkZVRpbWU7CiAgICAgICAgfSB2aWV3ODM4XzExNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI1NF07CiAgICAgICAgICAgIGYzMiB1bms4M0M7CiAgICAgICAgfSB2aWV3ODNDXzExNTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI1NF07CiAgICAgICAgICAgIGYzMiBidW1wOwogICAgICAgIH0gdmlldzgzQ18xMTY7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyNThdOwogICAgICAgICAgICBzMzIgdW5rODQwOwogICAgICAgIH0gdmlldzg0MF8xMTc7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyNThdOwogICAgICAgICAgICBzMzIgc3VyZmFjZWQ7CiAgICAgICAgfSB2aWV3ODQwXzExODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI2NF07CiAgICAgICAgICAgIHMzMiB1bms4NEM7CiAgICAgICAgfSB2aWV3ODRDXzE0OTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI2Q107CiAgICAgICAgICAgIGYzMiB1bms4NTQ7CiAgICAgICAgfSB2aWV3ODU0XzE0NzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI3NF07CiAgICAgICAgICAgIHMzMiB1bms4NUM7CiAgICAgICAgfSB2aWV3ODVDXzExOTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI3NF07CiAgICAgICAgICAgIHMzMiB3ODVDOwogICAgICAgIH0gdmlldzg1Q18xMjA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyN0NdOwogICAgICAgICAgICBzMzIgdW5rODY0OwogICAgICAgIH0gdmlldzg2NF8xMjE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgyN0NdOwogICAgICAgICAgICBzMzIgZjg2NDsKICAgICAgICB9IHZpZXc4NjRfMTIyOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MjgwXTsKICAgICAgICAgICAgczMyIHVuazg2ODsKICAgICAgICB9IHZpZXc4NjhfMTIzOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MjgwXTsKICAgICAgICAgICAgczMyIGY4Njg7CiAgICAgICAgfSB2aWV3ODY4XzEyNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI4NF07CiAgICAgICAgICAgIHMzMiB1bms4NkM7CiAgICAgICAgfSB2aWV3ODZDXzEyNTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI4NF07CiAgICAgICAgICAgIHMzMiBwYXJhbWV0ZXI7CiAgICAgICAgfSB2aWV3ODZDXzEyNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI4NF07CiAgICAgICAgICAgIHMzMiBhbmltYXRpb247CiAgICAgICAgfSB2aWV3ODZDXzEyNzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI4OF07CiAgICAgICAgICAgIHMzMiB1bms4NzA7CiAgICAgICAgfSB2aWV3ODcwXzE1NzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDI5MF07CiAgICAgICAgICAgIFNoYXJlZF9FZmZlY3QgZWZmZWN0OwogICAgICAgIH0gdmlldzg3OF8xNTg7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgzNTBdOwogICAgICAgICAgICBjaGFyIHVuazkzOFsyMTg4XTsKICAgICAgICB9IHZpZXc5MzhfMTI4OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4MzUwXTsKICAgICAgICAgICAgY2hhciBzdHJva2VzWzIxODhdOwogICAgICAgIH0gdmlldzkzOF8xMjk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHgzNTBdOwogICAgICAgICAgICBjaGFyIHN0cm9rZXNbMjE4OF07CiAgICAgICAgfSB2aWV3OTM4XzEzMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDM1MF07CiAgICAgICAgICAgIHMzMiB1bms5Mzg7CiAgICAgICAgfSB2aWV3OTM4XzE2MjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDZEMF07CiAgICAgICAgICAgIHMzMiB1bmtDQjg7CiAgICAgICAgfSB2aWV3Q0I4XzE2MzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDZFNF07CiAgICAgICAgICAgIHMzMiB1bmtDQ0M7CiAgICAgICAgfSB2aWV3Q0NDXzE2NDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDc1OF07CiAgICAgICAgICAgIHMzMiB1bmtENDA7CiAgICAgICAgfSB2aWV3RDQwXzE2NTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDk2Q107CiAgICAgICAgICAgIHMzMiB1bmtGNTQ7CiAgICAgICAgfSB2aWV3RjU0XzEzMTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDk2Q107CiAgICAgICAgICAgIHMzMiBzZWxlY3Rpb247CiAgICAgICAgfSB2aWV3RjU0XzEzMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDlBOF07CiAgICAgICAgICAgIHMzMiB1bmtGOTA7CiAgICAgICAgfSB2aWV3RjkwXzEzMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweDlBOF07CiAgICAgICAgICAgIHMzMiBjaG9pY2U7CiAgICAgICAgfSB2aWV3RjkwXzEzNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEJDQ107CiAgICAgICAgICAgIHMzMiB1bmsxMUI0OwogICAgICAgIH0gdmlldzExQjRfMTM1OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QkNDXTsKICAgICAgICAgICAgczMyIGxvY2tlZDsKICAgICAgICB9IHZpZXcxMUI0XzEzNjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEJEMF07CiAgICAgICAgICAgIHMzMiB1bmsxMUI4OwogICAgICAgIH0gdmlldzExQjhfMTM3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QkQwXTsKICAgICAgICAgICAgczMyIGZyb3plbjsKICAgICAgICB9IHZpZXcxMUI4XzEzODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEJENF07CiAgICAgICAgICAgIHMzMiB1bmsxMUJDOwogICAgICAgIH0gdmlldzExQkNfMTM5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QkQ0XTsKICAgICAgICAgICAgczMyIGYxMUJDOwogICAgICAgIH0gdmlldzExQkNfMTQwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QkQ4XTsKICAgICAgICAgICAgczMyIHVuazExQzA7CiAgICAgICAgfSB2aWV3MTFDMF8xNDE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhCRDhdOwogICAgICAgICAgICBzMzIgZjExQzA7CiAgICAgICAgfSB2aWV3MTFDMF8xNDI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhCRENdOwogICAgICAgICAgICBmMzIgdW5rMTFDNDsKICAgICAgICB9IHZpZXcxMUM0XzE0MzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEJEQ107CiAgICAgICAgICAgIGYzMiBzb3VuZFRpbWU7CiAgICAgICAgfSB2aWV3MTFDNF8xNDQ7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhCRTRdOwogICAgICAgICAgICBzMzIgdW5rMTFDQzsKICAgICAgICB9IHZpZXcxMUNDXzE0NTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEJFNF07CiAgICAgICAgICAgIHMzMiBmMTFDQzsKICAgICAgICB9IHZpZXcxMUNDXzE0NjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEJGMF07CiAgICAgICAgICAgIGYzMiB1bmsxMUQ4OwogICAgICAgIH0gdmlldzExRDhfMTQ3OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QkYwXTsKICAgICAgICAgICAgZjMyIHJlY29pbDsKICAgICAgICB9IHZpZXcxMUQ4XzE0ODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEJGMF07CiAgICAgICAgICAgIGYzMiBzdHVuOwogICAgICAgIH0gdmlldzExRDhfMTQ5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QkY0XTsKICAgICAgICAgICAgZjMyIHVuazExREM7CiAgICAgICAgfSB2aWV3MTFEQ18xODU7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhCRjhdOwogICAgICAgICAgICBmMzIgdW5rMTFFMDsKICAgICAgICB9IHZpZXcxMUUwXzE4NjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEMwMF07CiAgICAgICAgICAgIHMzMiB1bmsxMUU4OwogICAgICAgIH0gdmlldzExRThfMTUwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QzAwXTsKICAgICAgICAgICAgczMyIGYxMUU4OwogICAgICAgIH0gdmlldzExRThfMTUxOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QzA0XTsKICAgICAgICAgICAgZjMyIHVuazExRUM7CiAgICAgICAgfSB2aWV3MTFFQ18xODk7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDMjhdOwogICAgICAgICAgICBzMzIgdW5rMTIxMDsKICAgICAgICB9IHZpZXcxMjEwXzE1MjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEMyOF07CiAgICAgICAgICAgIHMzMiBtYXJrZXI7CiAgICAgICAgfSB2aWV3MTIxMF8xNTM7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDMkNdOwogICAgICAgICAgICBzMzIgdW5rMTIxNDsKICAgICAgICB9IHZpZXcxMjE0XzE1NDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEMyQ107CiAgICAgICAgICAgIHMzMiBtYXJrZXI7CiAgICAgICAgfSB2aWV3MTIxNF8xNTU7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDMkNdOwogICAgICAgICAgICBzMzIgbWFya2VyU2hvd247CiAgICAgICAgfSB2aWV3MTIxNF8xNTY7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDMzBdOwogICAgICAgICAgICBzMzIgdW5rMTIxODsKICAgICAgICB9IHZpZXcxMjE4XzE1NzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEMzMF07CiAgICAgICAgICAgIHMzMiBmMTIxODsKICAgICAgICB9IHZpZXcxMjE4XzE1ODsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBjaGFyIHBhZFsweEMzNF07CiAgICAgICAgICAgIHMzMiB1bmsxMjFDOwogICAgICAgIH0gdmlldzEyMUNfMTU5OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QzM0XTsKICAgICAgICAgICAgczMyIGYxMjFDOwogICAgICAgIH0gdmlldzEyMUNfMTYwOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIGNoYXIgcGFkWzB4QzM4XTsKICAgICAgICAgICAgczMyIHVuazEyMjA7CiAgICAgICAgfSB2aWV3MTIyMF8xNjE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgY2hhciBwYWRbMHhDMzhdOwogICAgICAgICAgICBzMzIgZjEyMjA7CiAgICAgICAgfSB2aWV3MTIyMF8xNjI7CiAgICAgICAgc3RydWN0IHsgY2hhciBwYWRbMHhFXTsgczE2IGNoYXJnZTsgfSBjaGFyZ2VWaWV3OwogICAgICAgIHN0cnVjdCB7IGNoYXIgcGFkWzB4MTFGNCAtIDB4NUU4XTsgZjMyIHNwaW47IHMzMiBmcmFtZTsgfSByYXBpZEZpcmVWaWV3OwogICAgfSB2aWV3czVFODsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICB1MzIgdW5rMTIyQzsKICAgICAgICB9IHZpZXcxMjJDXzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgdTMyIGZsYWdzOwogICAgICAgIH0gdmlldzEyMkNfMTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgb3B0aW9uczsKICAgICAgICB9IHZpZXcxMjJDXzI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIGYxMjJDOwogICAgICAgIH0gdmlldzEyMkNfMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgZnhGbGFnczsKICAgICAgICB9IHZpZXcxMjJDXzQ7CiAgICB9IHZpZXdzMTIyQzsKICAgIGYzMiBmeFRpbWU7CiAgICBmMzIgZnhTcGVlZDsKICAgIHMzMiBmeFN0YWdlOwogICAgY2hhciBwYWQxMjNDWzB4NF07CiAgICBmMzIgdW5rMTI0MDsKICAgIGYzMiB1bmsxMjQ0OwogICAgY2hhciBwYWQxMjQ4WzB4N0NdOwogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiB1bmsxMkM0OwogICAgICAgIH0gdmlldzEyQzRfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgZjEyQzQ7CiAgICAgICAgfSB2aWV3MTJDNF8xOwogICAgfSB2aWV3czEyQzQ7CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHVuazEyQzg7CiAgICAgICAgfSB2aWV3MTJDOF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBmMTJDODsKICAgICAgICB9IHZpZXcxMkM4XzE7CiAgICB9IHZpZXdzMTJDODsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgdW5rMTJDQ1s4XTsKICAgICAgICB9IHZpZXcxMkNDXzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHNwbGl0c0FbOF07CiAgICAgICAgfSB2aWV3MTJDQ18xOwogICAgfSB2aWV3czEyQ0M7CiAgICBzMzIgdW5rMTJFQzsKICAgIGNoYXIgcGFkMTJGMFsweDRdOwogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiB1bmsxMkY0WzhdOwogICAgICAgIH0gdmlldzEyRjRfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgc3BsaXRzQls4XTsKICAgICAgICB9IHZpZXcxMkY0XzE7CiAgICB9IHZpZXdzMTJGNDsKICAgIGNoYXIgcGFkMTMxNFsweDIwXTsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgdW5rMTMzNDsKICAgICAgICB9IHZpZXcxMzM0XzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIGYxMzM0OwogICAgICAgIH0gdmlldzEzMzRfMTsKICAgIH0gdmlld3MxMzM0OwogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiB1bmsxMzM4OwogICAgICAgIH0gdmlldzEzMzhfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgZjEzMzg7CiAgICAgICAgfSB2aWV3MTMzOF8xOwogICAgfSB2aWV3czEzMzg7CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHVuazEzM0M7CiAgICAgICAgfSB2aWV3MTMzQ18wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBsYXBzOwogICAgICAgIH0gdmlldzEzM0NfMTsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgbGl2ZXM7CiAgICAgICAgfSB2aWV3MTMzQ18yOwogICAgfSB2aWV3czEzM0M7CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHVuazEzNDA7CiAgICAgICAgfSB2aWV3MTM0MF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBzdGFsbHM7CiAgICAgICAgfSB2aWV3MTM0MF8xOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiB0aW1lcjsKICAgICAgICB9IHZpZXcxMzQwXzI7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHJlc3Bhd25UaW1lcjsKICAgICAgICB9IHZpZXcxMzQwXzM7CiAgICB9IHZpZXdzMTM0MDsKICAgIGNoYXIgcGFkMTM0NFsweDcwXTsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzdHJ1Y3QgU3RhdGVJbmZvICogdW5rMTNCNDsKICAgICAgICB9IHZpZXcxM0I0XzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IFN0YXRlSW5mbyAqIHN0YXRlczsKICAgICAgICB9IHZpZXcxM0I0XzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IE1vZGUgKiB1bmsxM0I0OwogICAgICAgIH0gdmlldzEzQjRfMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICB2b2lkICogY2hhcmFjdGVyOwogICAgICAgIH0gdmlldzEzQjRfMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgZjEzQjQ7CiAgICAgICAgfSB2aWV3MTNCNF80OwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHN0cnVjdCBTaGFyZWRfU3RhdGVJbmZvICogc3RhdGVzOwogICAgICAgIH0gdmlldzEzQjRfNTsKICAgIH0gdmlld3MxM0I0OwogICAgY2hhciBwYWQxM0I4WzB4MTBdOwogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiB1bmsxM0M4OwogICAgICAgIH0gdmlldzEzQzhfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgdzEzQzg7CiAgICAgICAgfSB2aWV3MTNDOF8xOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBmMTNDODsKICAgICAgICB9IHZpZXcxM0M4XzI7CiAgICB9IHZpZXdzMTNDODsKICAgIGNoYXIgcGFkMTNDQ1sweDhdOwogICAgczMyIHVuazEzRDQ7CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IEhlbGQgKiB1bmsxM0Q4OwogICAgICAgIH0gdmlldzEzRDhfMDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzdHJ1Y3QgSGVsZCAqIGhlbGQ7CiAgICAgICAgfSB2aWV3MTNEOF8xOwogICAgfSB2aWV3czEzRDg7CiAgICBjaGFyIHBhZDEzRENbMHhDXTsKICAgIHMzMiBtZXNzYWdlSW5kZXg7CiAgICBjaGFyIHBhZDEzRUNbMHg2NF07CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHVuazE0NTA7CiAgICAgICAgfSB2aWV3MTQ1MF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBjb21wdXRlcjsKICAgICAgICB9IHZpZXcxNDUwXzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIGluZmluaXRlOwogICAgICAgIH0gdmlldzE0NTBfMjsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgdW5saW1pdGVkOwogICAgICAgIH0gdmlldzE0NTBfMzsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgdW5jb3VudGVkOwogICAgICAgIH0gdmlldzE0NTBfNDsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBzMzIgZjE0NTA7CiAgICAgICAgfSB2aWV3MTQ1MF81OwogICAgfSB2aWV3czE0NTA7CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHVuazE0NTQ7CiAgICAgICAgfSB2aWV3MTQ1NF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBmMTQ1NDsKICAgICAgICB9IHZpZXcxNDU0XzE7CiAgICB9IHZpZXdzMTQ1NDsKICAgIGNoYXIgcGFkMTQ1OFsweENdOwogICAgdW5pb24gewogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIFZlYzMgdW5rMTQ2NDsKICAgICAgICB9IHZpZXcxNDY0XzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgVmVjMyBhaW07CiAgICAgICAgfSB2aWV3MTQ2NF8xOwogICAgfSB2aWV3czE0NjQ7CiAgICBjaGFyIHBhZDE0NzBbMHgxMF07CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgTWF0cml4IHVuazE0ODBbMl07CiAgICAgICAgfSB2aWV3MTQ4MF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIE1hdHJpeCBiZWFtc1syXTsKICAgICAgICB9IHZpZXcxNDgwXzE7CiAgICB9IHZpZXdzMTQ4MDsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBNYXRyaXggdW5rMTUwMFsyXTsKICAgICAgICB9IHZpZXcxNTAwXzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgTWF0cml4IGxhc2Vyc1syXTsKICAgICAgICB9IHZpZXcxNTAwXzE7CiAgICB9IHZpZXdzMTUwMDsKICAgIHVuaW9uIHsKICAgICAgICBzdHJ1Y3QgewogICAgICAgICAgICBNYXRyaXggdW5rMTU4MFsyXTsKICAgICAgICB9IHZpZXcxNTgwXzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgTWF0cml4IGRvdHNbMl07CiAgICAgICAgfSB2aWV3MTU4MF8xOwogICAgfSB2aWV3czE1ODA7CiAgICBjaGFyIHBhZDE2MDBbMHhENF07CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgczMyIHVuazE2RDQ7CiAgICAgICAgfSB2aWV3MTZENF8wOwogICAgICAgIHN0cnVjdCB7CiAgICAgICAgICAgIHMzMiBmMTZENDsKICAgICAgICB9IHZpZXcxNkQ0XzE7CiAgICB9IHZpZXdzMTZENDsKICAgIHUxNiB1bmsxNkQ4OwogICAgY2hhciBwYWQxNkRBWzB4Nl07CiAgICB1bmlvbiB7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IFNoYXJlZFBsYXllcl9mdW5jXzgwNDA4QzRDX2RlICogdW5rMTZFMDsKICAgICAgICB9IHZpZXcxNkUwXzA7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IFNoYXJlZFBsYXllcl9mdW5jXzgwNDA4QzRDX2RlICogbmV4dDsKICAgICAgICB9IHZpZXcxNkUwXzE7CiAgICAgICAgc3RydWN0IHsKICAgICAgICAgICAgc3RydWN0IFNoYXJlZFBsYXllcl9mdW5jXzgwNDA4QzRDX2RlICogbmV4dDsKICAgICAgICB9IHZpZXcxNkUwXzI7CiAgICB9IHZpZXdzMTZFMDsKfTsK */

struct Menu_func_80408C4C_de;
struct Menu_func_80408C4C_de;
struct Menu_func_80408C4C_de {
    char pad0[0x1C];
    SharedPlayer_func_80408C4C_de *player;
    func_80242278_S1 *slot;
    char *prompt;
};

/* unbake evidence input: c3RydWN0IE1lbnVfZnVuY184MDQwOEM0Q19kZTsKc3RydWN0IE1lbnVfZnVuY184MDQwOEM0Q19kZSB7CiAgICBjaGFyIHBhZDBbMHgxQ107CiAgICBTaGFyZWRQbGF5ZXJfZnVuY184MDQwOEM0Q19kZSAqcGxheWVyOwogICAgZnVuY184MDI0MjI3OF9TMSAqc2xvdDsKICAgIGNoYXIgKnByb21wdDsKfTsK */

struct PakRecord;
struct PakRecord;
struct PakRecord {
    u8 present;
    char pad[7];
    char pak[0x68];
};

/* unbake evidence input: c3RydWN0IFBha1JlY29yZDsKc3RydWN0IFBha1JlY29yZCB7CiAgICB1OCBwcmVzZW50OwogICAgY2hhciBwYWRbN107CiAgICBjaGFyIHBha1sweDY4XTsKfTsK */

struct Record_func_80405CA8_de;
struct Record_func_80405CA8_de;
struct Record_func_80405CA8_de {
    s32 a;
    s32 b;
    s32 c;
    s32 values[3];
    s32 d;
    s32 e;
};

/* unbake evidence input: c3RydWN0IFJlY29yZF9mdW5jXzgwNDA1Q0E4X2RlOwpzdHJ1Y3QgUmVjb3JkX2Z1bmNfODA0MDVDQThfZGUgewogICAgczMyIGE7CiAgICBzMzIgYjsKICAgIHMzMiBjOwogICAgczMyIHZhbHVlc1szXTsKICAgIHMzMiBkOwogICAgczMyIGU7Cn07Cg== */

struct Shared_func_804069F4_S1;
struct func_8021846C_S3;
struct Shared_func_804069F4_S1;
struct func_8021846C_S3;
struct Shared_func_804069F4_S1 {
    char pad0[0x1C];
    s32 first;
    struct func_8021846C_S3 * second;
};

/* unbake evidence input: c3RydWN0IFNoYXJlZF9mdW5jXzgwNDA2OUY0X1MxOwpzdHJ1Y3QgZnVuY184MDIxODQ2Q19TMzsKc3RydWN0IFNoYXJlZF9mdW5jXzgwNDA2OUY0X1MxIHsKICAgIGNoYXIgcGFkMFsweDFDXTsKICAgIHMzMiBmaXJzdDsKICAgIHN0cnVjdCBmdW5jXzgwMjE4NDZDX1MzICogc2Vjb25kOwp9Owo= */

struct func_80408C78_S1;
struct func_80408C78_S1;
struct func_80408C78_S1 {
    u16 unk0;
    char pad0[0x2 - 0x0 - sizeof(u16)];
    u16 unk2;
    char pad2[0x4 - 0x2 - sizeof(u16)];
    u16 unk4;
    char pad4[0x6 - 0x4 - sizeof(u16)];
    u16 unk6;
};

/* unbake evidence input: c3RydWN0IGZ1bmNfODA0MDhDNzhfUzE7CnN0cnVjdCBmdW5jXzgwNDA4Qzc4X1MxIHsKICAgIHUxNiB1bmswOwogICAgY2hhciBwYWQwWzB4MiAtIDB4MCAtIHNpemVvZih1MTYpXTsKICAgIHUxNiB1bmsyOwogICAgY2hhciBwYWQyWzB4NCAtIDB4MiAtIHNpemVvZih1MTYpXTsKICAgIHUxNiB1bms0OwogICAgY2hhciBwYWQ0WzB4NiAtIDB4NCAtIHNpemVvZih1MTYpXTsKICAgIHUxNiB1bms2Owp9Owo= */

extern void func_8040570C_de(u8 *arg0, s8 *arg1, s32 arg2);
extern int func_804058B0_de(struct Record_func_80405CA8_de * arg0);
extern void func_80405CA8_de(struct Record_func_80405CA8_de *record);
extern void func_80405CDC_de(struct Shape_typemap_110 *arg0);
extern s32 func_804085E0_de(void *unused, Menu_func_804085E0_de *menu);
#endif
