#include "types.h"

/* 802631B0 remaps each mask in the five button-state words, stopping
 * on a zero input mask. ROM D19B0..D1A48, including the sentinel pair. */
enum ResidentControllerButton {
    RESIDENT_BUTTON_A = 0x8000,
    RESIDENT_BUTTON_B = 0x4000,
    RESIDENT_BUTTON_Z = 0x2000,
    RESIDENT_BUTTON_START = 0x1000,
    RESIDENT_BUTTON_D_UP = 0x800,
    RESIDENT_BUTTON_D_DOWN = 0x400,
    RESIDENT_BUTTON_D_LEFT = 0x200,
    RESIDENT_BUTTON_D_RIGHT = 0x100,
    RESIDENT_BUTTON_L = 0x20,
    RESIDENT_BUTTON_R = 0x10,
    RESIDENT_BUTTON_C_UP = 0x8,
    RESIDENT_BUTTON_C_DOWN = 0x4,
    RESIDENT_BUTTON_C_LEFT = 0x2,
    RESIDENT_BUTTON_C_RIGHT = 0x1,
};

struct ResidentButtonRemap {
    u32 inputMask;
    u32 outputMask;
};
struct ResidentButtonRemap D_800CBB70[19] = {
    {RESIDENT_BUTTON_A, RESIDENT_BUTTON_A},
    {RESIDENT_BUTTON_B, RESIDENT_BUTTON_B},
    {RESIDENT_BUTTON_L, RESIDENT_BUTTON_R},
    {RESIDENT_BUTTON_R, RESIDENT_BUTTON_L},
    {RESIDENT_BUTTON_Z, RESIDENT_BUTTON_Z},
    {RESIDENT_BUTTON_START, RESIDENT_BUTTON_START},
    {RESIDENT_BUTTON_D_UP, RESIDENT_BUTTON_C_UP},
    {RESIDENT_BUTTON_D_LEFT, RESIDENT_BUTTON_C_LEFT},
    {RESIDENT_BUTTON_D_RIGHT, RESIDENT_BUTTON_C_RIGHT},
    {RESIDENT_BUTTON_D_DOWN, RESIDENT_BUTTON_C_DOWN},
    {RESIDENT_BUTTON_C_UP, RESIDENT_BUTTON_D_UP},
    {RESIDENT_BUTTON_C_LEFT, RESIDENT_BUTTON_D_LEFT},
    {RESIDENT_BUTTON_C_RIGHT, RESIDENT_BUTTON_D_RIGHT},
    {RESIDENT_BUTTON_C_DOWN, RESIDENT_BUTTON_D_DOWN},
    {0x10000, 0x10000},
    {0x20000, 0x20000},
    {0x40000, 0x40000},
    {0x80000, 0x80000},
    {0, 0},
};
