/* Scrolling credits line table. 80290E6C draws each character string,
 * and 80291074 tests the final NULL through D_800D3E14_de[0].
 * All targets are genuine, already native-exact string producers. */
extern const char ragewars_credits_label_team_us_rev1[];
extern const char ragewars_credits_label_blank_us_rev1[];
struct MenuStrings_CCCEC;
extern const struct MenuStrings_CCCEC ragewars_resident_strings_CCCEC_us_rev1;
extern const char ragewars_credits_label_testers_us_rev1[];
struct MenuStrings_CC8A4;
extern const struct MenuStrings_CC8A4 ragewars_resident_strings_CC8A4_us_rev1;
extern const char ragewars_credits_label_producer_us_rev1[];
struct MenuStrings_CC658;
extern const struct MenuStrings_CC658 ragewars_resident_strings_CC658_us_rev1;
extern const char ragewars_credits_label_technicians_us_rev1[];
struct MenuStrings_CC164;
extern const struct MenuStrings_CC164 ragewars_resident_strings_CC164_us_rev1;

char *ragewars_credits_lines_us_rev1[264] = {
    (char *)ragewars_credits_label_team_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 1036,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 1024,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 1008,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 980,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 968,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 952,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 932,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 904,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 876,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 840,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 816,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 792,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 768,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 728,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 692,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 656,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 628,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 592,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 568,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 528,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 492,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 452,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 436,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 420,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 404,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 392,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 368,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 324,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 308,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 296,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 284,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 272,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 256,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 212,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 192,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 176,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 136,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 120,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 104,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 92,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 52,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 40,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 28,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 12,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 0,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_testers_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 1036,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 1020,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 1004,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 988,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 976,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 964,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 948,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 908,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 884,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 860,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 840,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 812,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 776,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 744,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 708,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 684,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 656,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 620,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 576,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 544,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 528,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 508,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 492,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 460,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 440,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 420,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 192,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 404,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 120,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 372,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 356,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 316,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 276,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 264,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 236,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 224,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 204,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 188,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 156,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 136,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 88,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 44,
    (char *)&ragewars_resident_strings_CC8A4_us_rev1 + 0,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_producer_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 564,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 544,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 528,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 512,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 488,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 472,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CCCEC_us_rev1 + 40,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 452,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 436,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 424,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 412,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 392,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 380,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 364,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 348,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 336,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 320,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 304,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 292,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 280,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_testers_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 264,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 248,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 236,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 220,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 204,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 188,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 172,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 160,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 144,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 132,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 116,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 100,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 84,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 72,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 48,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 36,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 16,
    (char *)&ragewars_resident_strings_CC658_us_rev1 + 0,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_technicians_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1244,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1228,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1212,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1196,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1168,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1156,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1132,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1116,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1100,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1088,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1068,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1040,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1024,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 1004,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 992,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 976,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 964,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 924,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 888,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 864,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 836,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 808,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 780,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 752,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 712,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 696,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 664,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 628,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 596,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 560,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 528,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 492,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 456,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 436,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 396,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 380,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 360,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 324,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 292,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 252,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 216,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 188,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 152,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 140,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 112,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 96,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)ragewars_credits_label_blank_us_rev1,
    (char *)&ragewars_resident_strings_CC164_us_rev1 + 56,
    0,
};
