char data_unresolved_800C65C8[8936] =
    "N DE MEMcontroller pak\0"
    "\0"
    "\0"
    "\0"
    "\0"
    "\0"
    "accessing the\0"
    "\0"
    "\0"
    "EXPANSION PAK FOUND\0"
    "PRESS ANY BUTTON\0"
    "\0"
    "\0"
    "\0"
    "VISIT OUR WEBSITE AT WWW.ACCLAIM.NET\0"
    "\0"
    "\0"
    "\0"
    "THEIR PATIENCE\0"
    "\0"
    "PAM, TRUMAN AND TUCKER FOR\0"
    "\0"
    "AND LILLY\0"
    "\0"
    "\0"
    "JIM DELBRIDGE, HAILEY, SEBASTIAN\0"
    "\0"
    "\0"
    "\0"
    "ANNA LANGSTON, SIMON SKEDD,\0"
    "RAMI FOR TEACHING ME ABOUT MONKEYS\0"
    "\0"
    "ANGELA FOR WAITING UP FOR ME AT NIGHT\0"
    "\0"
    "\0"
    "LORRAINE, BRITTANY AND KATIE\0"
    "\0"
    "\0"
    "\0"
    "GREY THANKS KAS, TS BEHR, AND BEN\0"
    "\0"
    "\0"
    "DAN HILL AND FAMILY\0"
    "MIKE MARQUES\0"
    "\0"
    "\0"
    "\0"
    "SHEA MACKIN, CADE, KYLAN, AND FAMILY\0"
    "\0"
    "\0"
    "\0"
    "HALF OF HIS TEAM\0"
    "\0"
    "\0"
    "\0"
    "JEFF EVERETT FOR LETTING US BORROW\0"
    "\0"
    "DAVID AND MATT AT SATELLITE STUDIO\0"
    "\0"
    "BROTHER. BE FREE. I MISS YOU.\0"
    "\0"
    "\0"
    "DR. DON T. HUEY, JR., D.C. - MY BIG\0"
    "FOR LETTING ME DO WHAT I LOVE!\0"
    "\0"
    "MARLENE AND RAYMOND PACINI - THANKS\0"
    "DAMARIS (COCO AND SNIKERS TOO!)\0"
    "JENNY COWLISHAW\0"
    "           ADDITIONAL SPECIAL THANKS TO\0"
    "OF WHY WE WERE NEVER HOME.\0"
    "\0"
    "SUPPORT AND UNDERSTANDING\0"
    "\0"
    "\0"
    "RAGE WARS TEAM FOR THEIR\0"
    "\0"
    "\0"
    "\0"
    "FRIENDS AND FAMILY OF THE\0"
    "\0"
    "\0"
    "THANK YOU TO ALL OF THE\0"
    "WE WOULD LIKE TO EXTEND A SPECIAL\0"
    "\0"
    "\0"
    "                      SPECIAL THANKS\0"
    "\0"
    "\0"
    "\0"
    "ED FORTUNE\0"
    "\0"
    "ONLINE EDITOR\0"
    "\0"
    "\0"
    "BOBBY SAHA\0"
    "\0"
    "INTERNET ARCHITECT\0"
    "\0"
    "BEN FISCHBACH\0"
    "\0"
    "\0"
    "SR. MANAGER ACCLAIM ONLINE\0"
    "\0"
    "MICHELLE SEEBACH\0"
    "\0"
    "\0"
    "\0"
    "PR MANAGER\0"
    "\0"
    "JACK SCALICI\0"
    "\0"
    "\0"
    "\0"
    "JP CARNOVALE\0"
    "\0"
    "\0"
    "\0"
    "MARKETING GAME ANALYST\0"
    "\0"
    "DON JACKSON\0"
    "MARKETING PRODUCT MANAGER\0"
    "\0"
    "\0"
    "ULISES BATALLA\0"
    "\0"
    "CHRIS FRISONE\0"
    "\0"
    "\0"
    "MIKE STERZEL\0"
    "\0"
    "\0"
    "\0"
    "CHRIS ZINO\0"
    "\0"
    "TECHNICIANS\0"
    "ANTHONY GENTILE\0"
    "TURNOVER TECHNICIAN\0"
    "CHRIS MAHER\0"
    "TURNOVER COORDINATOR\0"
    "\0"
    "\0"
    "\0"
    "MAX IMAS\0"
    "\0"
    "\0"
    "\0"
    "LLOYD THOMPSON\0"
    "\0"
    "MARK BERKOWITZ\0"
    "\0"
    "JAY CAPOZELLO\0"
    "\0"
    "\0"
    "DJ PELUSO\0"
    "\0"
    "\0"
    "PAUL JOHNSON\0"
    "\0"
    "\0"
    "\0"
    "JOE CARBONE\0"
    "MAURICE PHILIPS\0"
    "SCOTT SNOPOWSKI\0"
    "LUC ANGRAND II\0"
    "\0"
    "BRHETT HOHWALD\0"
    "\0"
    "DAN BADILLA\0"
    "JOSHUA ROGERS\0"
    "\0"
    "\0"
    "PAUL DICARLO\0"
    "\0"
    "\0"
    "\0"
    "JON NICOLAI\0"
    "CHRIS RAPPO\0"
    "PROJECT LEADS\0"
    "\0"
    "\0"
    "MATT CANONICO\0"
    "\0"
    "\0"
    "MARK GARONE\0"
    "LEAD ANALYSTS\0"
    "\0"
    "\0"
    "MIKE PATTERSON\0"
    "\0"
    "BRIAN REGAN\0"
    "SENIOR LEAD ANALYST\0"
    "JEFF ROSA\0"
    "\0"
    "\0"
    "DALE TAYLOR\0"
    "QA SUPERVISOR\0"
    "\0"
    "\0"
    "CAROL CARACCIOLO\0"
    "\0"
    "\0"
    "\0"
    "BILL DICKSON\0"
    "\0"
    "\0"
    "\0"
    "MANUAL SUPPORT MANAGER\0"
    "\0"
    "NICOLE RUISI\0"
    "\0"
    "\0"
    "\0"
    "KATHLEEN BYRNE\0"
    "\0"
    "PROJECT TRACKING\0"
    "\0"
    "\0"
    "\0"
    "JAMES DALY\0"
    "\0"
    "PRODUCER\0"
    "\0"
    "\0"
    "\0"
    "                  NY PRODUCT DEVELOPMENT\0"
    "\0"
    "\0"
    "\0"
    "                ACCLAIM ENTERTAINMENT INC.\0"
    "\0"
    "                           PUBLISHER CREDITS\0"
    "\0"
    "\0"
    "\0"
    "DARREN STUBBINGTON\0"
    "\0"
    "EXECUTIVE VP OF ACCLAIM STUDIOS\0"
    "CRAIG GALLEY\0"
    "\0"
    "\0"
    "\0"
    "VP OF TECHNOLOGY\0"
    "\0"
    "\0"
    "\0"
    "CYRUS LUM\0"
    "\0"
    "\0"
    "VP OF DIGITAL PRODUCTIONS\0"
    "\0"
    "\0"
    "NIGEL COOK\0"
    "\0"
    "VP OF PRODUCT DEVELOPMENT AND DESIGN\0"
    "\0"
    "\0"
    "\0"
    "                       GLOBAL DIRECTORS\0"
    "ALAN JOHNSON\0"
    "\0"
    "\0"
    "\0"
    "DIRECTOR OF DIGITAL PRODUCTIONS\0"
    "AUDIO MANAGER\0"
    "\0"
    "\0"
    "CREATIVE DIRECTOR\0"
    "\0"
    "\0"
    "MALCOLM CRUMMACK\0"
    "\0"
    "\0"
    "\0"
    "DIRECTOR OF PRODUCT DEVELOPMENT\0"
    "STEVEN BROUMLEY\0"
    "TECHNICAL DIRECTOR\0"
    "\0"
    "RUSSELL BYRD\0"
    "\0"
    "\0"
    "\0"
    "GM OF ACCLAIM STUDIOS AUSTIN\0"
    "\0"
    "\0"
    "\0"
    "        ACCLAIM STUDIOS AUSTIN DIRECTORS\0"
    "\0"
    "\0"
    "\0"
    "MARC SCHAEFGEN - LORD OF THE DEAD\0"
    "\0"
    "\0"
    "TITOS MENCHACA - TAL SET\0"
    "\0"
    "\0"
    "\0"
    "DOUG FORREST - BASTILLE\0"
    "JOSE BROWN - OBLIVION / GUARDIAN\0"
    "\0"
    "\0"
    "\0"
    "DAVID DIENSTBIER - CAMPAIGNER\0"
    "\0"
    "\0"
    "DAVID KRAUSE - FIREBORN / DINOSOIDS\0"
    "JESSICA ROBERTSON - SYRA\0"
    "\0"
    "\0"
    "\0"
    "TODD LOWE - PURLIN\0"
    "\0"
    "BERNADETTE NASON - ADON\0"
    "TRAVIS DAVIS - TUROK\0"
    "\0"
    "\0"
    "\0"
    "                       CHARACTER VOICES\0"
    "JUSTIN WITHERS\0"
    "\0"
    "SHANE TATE\0"
    "\0"
    "JIM STRONG\0"
    "\0"
    "BRANDON ROWLETT\0"
    "MARK RICHARDS\0"
    "\0"
    "\0"
    "CHRIS KENDALL\0"
    "\0"
    "\0"
    "JERREMY ARNSTON\0"
    "                                   TESTERS\0"
    "\0"
    "RUSS BREWER\0"
    "PROJECT LEAD\0"
    "\0"
    "\0"
    "\0"
    "TODD DOWD\0"
    "\0"
    "\0"
    "QA MANAGER\0"
    "\0"
    "                           AUSTIN QA\0"
    "\0"
    "\0"
    "\0"
    "JOHN HENKE\0"
    "\0"
    "MARC SCHAEFGEN\0"
    "\0"
    "DARREN MITCHELL\0"
    "                           SOUND DESIGN\0"
    "BEY BICKERTON\0"
    "\0"
    "\0"
    "DAVID DIENSTBIER\0"
    "\0"
    "\0"
    "\0"
    "                       ADDITIONAL DESIGN\0"
    "\0"
    "\0"
    "\0"
    "BRIAN WATSON\0"
    "\0"
    "\0"
    "\0"
    "DAVID SMITH\0"
    "ANDY ONEIL\0"
    "\0"
    "STEVAN HIRD\0"
    "STEVE BROUMLEY\0"
    "\0"
    "                   ADDITIONAL PROGRAMMING\0"
    "\0"
    "\0"
    "DIGITAL IMAGING GROUP\0"
    "\0"
    "\0"
    "RYAN TRACY\0"
    "\0"
    "ALEX OMLANSKY\0"
    "\0"
    "\0"
    "PETER FRANCO\0"
    "\0"
    "\0"
    "\0"
    "SCOTT BROCKER\0"
    "\0"
    "\0"
    "                         ADDITIONAL ART\0"
    "ROB WHITAKER - DIGITAL PRODUCTIONS\0"
    "\0"
    "ROBERT WILSHER - DIGITAL PRODUCTIONS\0"
    "\0"
    "\0"
    "\0"
    "JEFF SHELTON - DESIGN\0"
    "\0"
    "\0"
    "ROBBIE MILLER - DIGITAL PRODUCTIONS\0"
    "PAUL MASTERS - PROGRAMMING\0"
    "\0"
    "BRAD MARQUES - DIGITAL PRODUCTIONS\0"
    "\0"
    "MARC MACKIN - DIGITAL PRODUCTIONS\0"
    "\0"
    "\0"
    "TREVOR LEMOINE - DIGITAL PRODUCTIONS\0"
    "\0"
    "\0"
    "\0"
    "MATT KYLE - PROGRAMMING\0"
    "MICHAEL HUEY - DESIGN\0"
    "\0"
    "\0"
    "NEILL GLANCY - DESIGN\0"
    "\0"
    "\0"
    "MICHAEL FONG - DIGITAL PRODUCTIONS\0"
    "\0"
    "JIM COWLISHAW - PROGRAMMING\0"
    "BRUCE COONER - PROGRAMMING\0"
    "\0"
    "JASON BEHR - DESIGN\0"
    "MICHAEL DAUBERT\0"
    "LEAD ARTIST\0"
    "FRANCISCO JAVIER LAFUENTE\0"
    "\0"
    "\0"
    "LEAD PROGRAMMER\0"
    "MARK PACINI\0"
    "PROJECT MANAGER\0"
    "                           RAGE WARS TEAM\0"
    "\0"
    "\0"
    "acc\350s au\0"
    "\0"
    "\0"
    "\0"
    "EXTENSION DE MEMOIRE TROUVEE\0"
    "\0"
    "\0"
    "\0"
    "APPUYEZ SUR UN BOUTON\0"
    "\0"
    "\0"
    "NOTRE SITE INTERNET WWW.ACCLAIM.NET\0"
    "LEUR PATIENCE\0"
    "\0"
    "\0"
    "PAM, TRUMAN ET TUCKER POUR\0"
    "\0"
    "ET LILLY\0"
    "\0"
    "\0"
    "\0"
    "RAMI POUR SES SINGES\0"
    "\0"
    "\0"
    "\0"
    "ANGELA POUR SA PATIENCE\0"
    "LORRAINE, BRITTANY ET KATIE\0"
    "MERCI A KAS, TS BEHR ET BEN\0"
    "DAN HILL ET SA FAMILLE\0"
    "\0"
    "SHEA MACKIN, CADE, KYLAN ET LES AUTRES\0"
    "\0"
    "LA MOITIE DE SON EQUIPE\0"
    "JEFF EVERETT POUR NOUS AVOIR PRETE\0"
    "\0"
    "DAVID ET MATT (SATELLITE STUDIO)\0"
    "\0"
    "\0"
    "\0"
    "GRAND FRERE. TU ME MANQUES.\0"
    "DR. DON T. HUEY, JR., D.C. - MON\0"
    "\0"
    "\0"
    "\0"
    "DE M'AVOIR LAISSE FAIRE CE QUE J'AIME !\0"
    "MARLENE ET RAYMOND PACINI - MERCI\0"
    "\0"
    "\0"
    "DAMARIS (COCO ET SNIKERS)\0"
    "\0"
    "\0"
    "               AUTRES REMERCIEMENTS\0"
    "EN TOUTES CIRCONSTANCES.\0"
    "\0"
    "\0"
    "\0"
    "LEUR COMPREHENSION\0"
    "\0"
    "POUR LEUR SOUTIEN ET\0"
    "\0"
    "\0"
    "\0"
    "DES MEMBRES DE RAGE WARS\0"
    "\0"
    "\0"
    "\0"
    "LES AMIS ET LES FAMILLES\0"
    "\0"
    "\0"
    "\0"
    "NOUS VOUDRIONS REMERCIER\0"
    "\0"
    "\0"
    "\0"
    "                      REMERCIEMENTS\0"
    "EDITEUR ONLINE\0"
    "\0"
    "ARCHITECTE SITE INTERNET\0"
    "\0"
    "\0"
    "\0"
    "DIRECTEUR ACCLAIM ONLINE\0"
    "\0"
    "\0"
    "\0"
    "RESPONSABLE DES RELATIONS PUBLIQUES\0"
    "ANALYSTE MARKETING\0"
    "\0"
    "CHEF DE PRODUIT MARKETING\0"
    "\0"
    "\0"
    "TECHNICIENS\0"
    "TECHNICIEN ROTATION\0"
    "COORDINATEUR ROTATION\0"
    "\0"
    "\0"
    "                                  TESTEURS\0"
    "\0"
    "CHEFS DE PROJET\0"
    "ANALISTES PRINCIPAUX\0"
    "\0"
    "\0"
    "\0"
    "ANALISTE PRINCIPAL\0"
    "\0"
    "SUPERVISEUR QUELITE\0"
    "RESPONSABLE QUALITE\0"
    "RESPONSABLE MANUEL\0"
    "\0"
    "SUIVI DE PROJET\0"
    "PRODUCTEUR\0"
    "\0"
    "ACCLAIM STUDIOS\0"
    "TECHNOLOGIE\0"
    "PRODUCTION DIGITALE\0"
    "PRODUCTION ET DESIGN\0"
    "\0"
    "\0"
    "\0"
    "             DIRECTEURS\0"
    "DIRECTEUR PRODUCTION DIGITALE\0"
    "\0"
    "\0"
    "DIRECTEUR AUDIO\0"
    "DIRECTEUR CREATION\0"
    "\0"
    "DIRECTEUR DE PRODUCTION\0"
    "DIRECTEUR TECHNIQUE\0"
    "GM ACCLAIM STUDIOS AUSTIN\0"
    "\0"
    "\0"
    "COMITE DE DIRECTION ACCLAIM STUDIOS AUSTIN\0"
    "\0"
    "                     VOIX DES PERSONNAGES\0"
    "\0"
    "\0"
    "                                 TESTEURS\0"
    "\0"
    "\0"
    "                 ASSURANCE QUALITE AUSTIN\0"
    "\0"
    "\0"
    "                        CONCEPTION SONORE\0"
    "\0"
    "\0"
    "                       DESIGN ADDITIONNEL\0"
    "\0"
    "\0"
    "                PROGRAMMEURS ADDITIONNELS\0"
    "\0"
    "\0"
    "                    ARTISTES ADDITIONNELS\0"
    "\0"
    "\0"
    "ROB WHITAKER - PRODUCTION DIGITALE\0"
    "\0"
    "ROBERT WILSHER - PRODUCTION DIGITALE\0"
    "\0"
    "\0"
    "\0"
    "ROBBIE MILLER - PRODUCTION DIGITALE\0"
    "PAUL MASTERS - PROGRAMMATION\0"
    "\0"
    "\0"
    "\0"
    "BRAD MARQUES - PRODUCTION DIGITALE\0"
    "\0"
    "MARC MACKIN - PRODUCTION DIGITALE\0"
    "\0"
    "\0"
    "TREVOR LEMOINE - PRODUCTION DIGITALE\0"
    "\0"
    "\0"
    "\0"
    "MATT KYLE - PROGRAMMATION\0"
    "\0"
    "\0"
    "MICHAEL FONG - PRODUCTION DIGITALE\0"
    "\0"
    "JIM COWLISHAW - PROGRAMMATION\0"
    "\0"
    "\0"
    "BRUCE COONER - PROGRAMMATION\0"
    "\0"
    "\0"
    "\0"
    "ARTISTE PRINCIPAL\0"
    "\0"
    "\0"
    "PROGRAMMEUR PRINCIPAL\0"
    "\0"
    "\0"
    "DIRECTEUR DE PROJET\0"
    "                   EQUIPE RAGE WARS\0"
    "accesso al\0"
    "\0"
    "EXPANSION PAK TROVATO\0"
    "\0"
    "\0"
    "PREMI UN BOTTONE\0"
    "\0"
    "\0"
    "\0"
    "VISITA IL NOSTRO SITO WWW.ACCLAIM.NET\0"
    "\0"
    "\0"
    "LA LORO PAZIENZA\0"
    "\0"
    "\0"
    "\0"
    "PAM, TRUMAN E TUCKER PER\0"
    "\0"
    "\0"
    "\0"
    "E LILLY\0"
    "RAMI PER AVERMI INSEGNATO QUALCOSA SULLE SCIMMIE\0"
    "\0"
    "\0"
    "\0"
    "ANGELA PER ASPETTARMI SVEGLIA LA NOTTE\0"
    "\0"
    "LORRAINE, BRITTANY E KATIE\0"
    "\0"
    "GREY RINGRAZIA  KAS, TS BEHR, E BEN\0"
    "DAN HILL E FAMIGLIA\0"
    "SHEA MACKIN, CADE, KYLAN, E FAMIGLIA\0"
    "\0"
    "\0"
    "\0"
    "META' DEL SUO TEAM\0"
    "\0"
    "JEFF EVERETT PER LASCIARCI UTILIZZARE\0"
    "\0"
    "\0"
    "DAVID E MATT AL SATELLITE STUDIO\0"
    "\0"
    "\0"
    "\0"
    "FRATELLO. SII LIBERO. MI MANCHI.\0"
    "\0"
    "\0"
    "\0"
    "PER LASCIARMI FARE CIO' CHE AMO!\0"
    "\0"
    "\0"
    "\0"
    "MARLENE E RAYMOND PACINI - GRAZIE\0"
    "\0"
    "\0"
    "DAMARIS (ANCHE COCO E SNIKERS!)\0"
    "           RINGRAZIAMENTI SPECIALI AGGIUNTIVI A\0"
    "PERCHc NON ERAVAMO MAI A CASA.\0"
    "\0"
    "SUPPORTARCI E CAPIRE IL \0"
    "\0"
    "\0"
    "\0"
    "DEL TEAM DI RAGE WARS PER\0"
    "\0"
    "\0"
    "AMICI E LE FAMIGLIE\0"
    "SPECIALE A TUTTI GLI\0"
    "\0"
    "\0"
    "\0"
    "VORREMMO ESTENDERE UN RINGRAZIAMENTO \0"
    "\0"
    "\0"
    "                      RINGRAZIAMENTI SPECIALI\0"
    "\0"
    "\0"
    "EDITOR ONLINE\0"
    "\0"
    "\0"
    "ARCHITETTO INTERNET\0"
    "RESPONSABILE ACCLAIM ONLINE\0"
    "RESPONSABILE PR\0"
    "ANALISTI MARKETING\0"
    "\0"
    "RESPONSABILE MARKETING\0"
    "\0"
    "TECNICI\0"
    "TECNICO TURNOVER\0"
    "\0"
    "\0"
    "\0"
    "COORDINATORE TURNOVER\0"
    "\0"
    "\0"
    "ANALISTI\0"
    "\0"
    "\0"
    "\0"
    "ANALISTA CAPO\0"
    "\0"
    "\0"
    "SUPERVISORE CONTROLLO QUALITf\0"
    "\0"
    "\0"
    "MANAGER DI SUPPORTO DEL MAUNALE\0"
    "GESTIONE DEL PROGETTO\0"
    "\0"
    "\0"
    "PRODUTTORE\0"
    "\0"
    "                  SVILUPPO DEL PRODOTTO A NY\0"
    "\0"
    "\0"
    "\0"
    "                  ACCLAIM ENTERTAINMENT INC.\0"
    "\0"
    "\0"
    "\0"
    "                           CREDITI DEL PRODUTTORE\0"
    "\0"
    "\0"
    "VP ESECUTIVO DELLA ACCLAIM STUDIOS\0"
    "\0"
    "VP DELLA TECNOLOGIA\0"
    "VP DELLE PRODUZIONI DIGITALI\0"
    "\0"
    "\0"
    "\0"
    "VP DELLO SVILUPPO DEL PRODOTTO E DEL DESIGN\0"
    "                       DIRETTORI GLOBALE\0"
    "\0"
    "\0"
    "\0"
    "DIRETTORE DELLE PRODUZIONI DIGITALI\0"
    "RESPONSABILE AUDIO\0"
    "\0"
    "DIRETTORE CREATIVO\0"
    "\0"
    "DIRETTORE DELLO SVILUPPO DEL PRODOTTO\0"
    "\0"
    "\0"
    "DIRETTORE TECNICO\0"
    "\0"
    "\0"
    "RESPOSNABILE ACCLAIM STUDIOS AUSTIN\0"
    "        DIRETTORI ACCLAIM STUDIOS AUSTIN \0"
    "\0"
    "\0"
    "                       VOCI DEI PERSONAGGI\0"
    "\0"
    "                                   TESTER\0"
    "\0"
    "\0"
    "CAPO DEL PROGETTO\0"
    "\0"
    "\0"
    "RESPONSABILE CONTROLLO QUALITf\0"
    "\0"
    "                           CONTROLLO QUALITf AUSTIN\0"
    "                           DESIGN AUDIO\0"
    "                   DESIGN AGGIUNTIVO\0"
    "\0"
    "\0"
    "\0"
    "                   PROGRAMMAZIONE AGGIUNTIVA\0"
    "\0"
    "\0"
    "\0"
    "GRUPPO DIGITALIZZAZIONE IMMAGINI\0"
    "\0"
    "\0"
    "\0"
    "                         ARTE AGGIUNTIVA\0"
    "\0"
    "\0"
    "\0"
    "ROB WHITAKER - PRODUZIONI DIGITALI\0"
    "\0"
    "ROBERT WILSHER - PRODUZIONI DIGITALI\0"
    "\0"
    "\0"
    "\0"
    "ROBBIE MILLER - PRODUZIONI DIGITALI\0"
    "PAUL MASTERS - PROGRAMMAZIONE\0"
    "\0"
    "\0"
    "BRAD MARQUES - PRODUZIONI DIGITALI\0"
    "\0"
    "MARC MACKIN - PRODUZIONI DIGITALI\0"
    "\0"
    "\0"
    "TREVOR LEMOINE - PRODUZIONI DIGITALI\0"
    "\0"
    "\0"
    "\0"
    "MATT KYLE - PROGRAMMAZIONE\0"
    "\0"
    "MICHAEL FONG - PRODUZIONI DIGITALI\0"
    "\0"
    "JIM COWLISHAW - PROGRAMMAZIONE\0"
    "\0"
    "BRUCE COONER - PROGRAMMAZIONE\0"
    "\0"
    "\0"
    "ARTISTA CAPO\0"
    "\0"
    "\0"
    "\0"
    "PROGRAMMATORE CAPO\0"
    "\0"
    "MANAGER DEL PROGETTO\0"
    "\200\0"
    "\0"
    "\0"
    "\0"
    "\0"
    "\0";
