char data_unresolved_800C62E8[4104] =
    "er pak\0"
    "\0"
    "controller pak\0"
    "\0"
    "\0"
    "\0"
    "\0"
    "\0"
    "zugriff auf das\0"
    "expansion pak gefunden\0"
    "\0"
    "DR\334CKE EINE TASTE\0"
    "\0"
    "\0"
    "BESUCHEN SIE UNSERE WEBSITE UNTER WWW.ACCLAIM.NET\0"
    "\0"
    "\0"
    "IHRE GEDULD\0"
    "PAM, TRUMAN UND TUCKER FbR\0"
    "\0"
    "UND LILLY\0"
    "\0"
    "\0"
    "JIM DELBRIDGE, HAILEY, SEBASTIAN\0"
    "\0"
    "\0"
    "\0"
    "ANNA LANGSTON, SIMON SKEDD,\0"
    "RAMI FbR ALLES, WAS SIE bBER AFFEN WEISS\0"
    "\0"
    "\0"
    "\0"
    "ANGELA, DAFbR; DASS SIE IN DER NACHT AUF MICH GEWARTET HAT\0"
    "\0"
    "LORRAINE, BRITTANY UND KATIE\0"
    "\0"
    "\0"
    "\0"
    "GREY THANKS KAS, TS BEHR UND BEN\0"
    "\0"
    "\0"
    "\0"
    "DAN HILL UND FAMILIE\0"
    "\0"
    "\0"
    "\0"
    "MIKE MARQUES\0"
    "\0"
    "\0"
    "\0"
    "SHEA MACKIN, CADE, KYLAN, UND FAMILIE\0"
    "\0"
    "\0"
    "HALBES TEAM GELIEHEN HAT\0"
    "\0"
    "\0"
    "\0"
    "JEFF EVERETT DAFbR; DASS ER UNS SEIN \0"
    "\0"
    "\0"
    "DAVID UND MATT IM SATELLITE-STUDIO\0"
    "\0"
    "BROTHER. ICH VERMISSE DICH.\0"
    "DR. DON T. HUEY, JR., D.C. - MEIN BIG\0"
    "\0"
    "\0"
    "DASS ICH TUN DURFTE; WAS MIR SPASS MACHT!\0"
    "\0"
    "\0"
    "MARLENE UND RAYMOND PACINI - DANKE,\0"
    "DAMARIS (AUCH COCO UND SNIKERS!)\0"
    "\0"
    "\0"
    "\0"
    "JENNY COWLISHAW\0"
    "           NOCH MEHR DANK AN\0"
    "\0"
    "\0"
    "\0"
    "WAREN, DANKEN.\0"
    "\0"
    "VERSTeNDNIS, DASS WIR NIE ZUHAUSE\0"
    "\0"
    "\0"
    "IHRE UNTERSTbTZUNG UND IHR\0"
    "\0"
    "FREUNDEN UND FAMILIEN FbR\0"
    "\0"
    "\0"
    "WIR MnCHTEN BESONDERS UNSEREN \0"
    "\0"
    "                      BESONDERER DANK AN\0"
    "\0"
    "\0"
    "\0"
    "ED FORTUNE\0"
    "\0"
    "ONLINE-EDITOR\0"
    "\0"
    "\0"
    "BOBBY SAHA\0"
    "\0"
    "INTERNET-ARCHITEKT\0"
    "\0"
    "BEN FISCHBACH\0"
    "\0"
    "\0"
    "SR. MANAGER ACCLAIM ONLINE\0"
    "\0"
    "MICHELLE SEEBACH\0"
    "\0"
    "\0"
    "\0"
    "PR-MANAGER\0"
    "\0"
    "JACK SCALICI\0"
    "\0"
    "\0"
    "\0"
    "JP CARNOVALE\0"
    "\0"
    "\0"
    "\0"
    "MARKETING-SPIELANALYSE\0"
    "\0"
    "DON JACKSON\0"
    "MARKETING-PRODUKTMANAGER\0"
    "\0"
    "\0"
    "\0"
    "ULISES BATALLA\0"
    "\0"
    "CHRIS FRISONE\0"
    "\0"
    "\0"
    "MIKE STERZEL\0"
    "\0"
    "\0"
    "\0"
    "CHRIS ZINO\0"
    "\0"
    "TECHNIKER\0"
    "\0"
    "\0"
    "ANTHONY GENTILE\0"
    "TURNOVER-TECHNIKER\0"
    "\0"
    "CHRIS MAHER\0"
    "TURNOVER-KOORDINATOR\0"
    "\0"
    "\0"
    "\0"
    "MAX IMAS\0"
    "\0"
    "\0"
    "\0"
    "LLOYD THOMPSON\0"
    "\0"
    "MARK BERKOWITZ\0"
    "\0"
    "JAY CAPOZELLO\0"
    "\0"
    "\0"
    "DJ PELUSO\0"
    "\0"
    "\0"
    "PAUL JOHNSON\0"
    "\0"
    "\0"
    "\0"
    "JOE CARBONE\0"
    "MAURICE PHILIPS\0"
    "SCOTT SNOPOWSKI\0"
    "LUC ANGRAND II\0"
    "\0"
    "BRHETT HOHWALD\0"
    "\0"
    "DAN BADILLA\0"
    "JOSHUA ROGERS\0"
    "\0"
    "\0"
    "PAUL DICARLO\0"
    "\0"
    "\0"
    "\0"
    "JON NICOLAI\0"
    "CHRIS RAPPO\0"
    "PROJEKTLEITER\0"
    "\0"
    "\0"
    "MATT CANONICO\0"
    "\0"
    "\0"
    "MARK GARONE\0"
    "ANALYSE\0"
    "MIKE PATTERSON\0"
    "\0"
    "BRIAN REGAN\0"
    "LEITUNG ANALYSE\0"
    "JEFF ROSA\0"
    "\0"
    "\0"
    "DALE TAYLOR\0"
    "QS-LEITUNG\0"
    "\0"
    "CAROL CARACCIOLO\0"
    "\0"
    "\0"
    "\0"
    "QS-MANAGER\0"
    "\0"
    "BILL DICKSON\0"
    "\0"
    "\0"
    "\0"
    "HANDBUCH\0"
    "\0"
    "\0"
    "\0"
    "NICOLE RUISI\0"
    "\0"
    "\0"
    "\0"
    "KATHLEEN BYRNE\0"
    "\0"
    "JAMES DALY\0"
    "\0"
    "PRODUZENT\0"
    "\0"
    "\0"
    "                  NY PRODUCT DEVELOPMENT\0"
    "\0"
    "\0"
    "\0"
    "                ACCLAIM ENTERTAINMENT INC.\0"
    "\0"
    "                           PUBLISHER-CREDITS\0"
    "\0"
    "\0"
    "\0"
    "DARREN STUBBINGTON\0"
    "\0"
    "AUSFbHERENDER VP DER ACCLAIM STUDIOS\0"
    "\0"
    "\0"
    "\0"
    "CRAIG GALLEY\0"
    "\0"
    "\0"
    "\0"
    "VP TECHNOLOGIE\0"
    "\0"
    "CYRUS LUM\0"
    "\0"
    "\0"
    "VP FbR DIE DIGITALPRODUKTION \0"
    "\0"
    "\0"
    "NIGEL COOK\0"
    "\0"
    "VP FbR PRODUKTENTWICKLUNG UND DESIGN\0"
    "\0"
    "\0"
    "\0"
    "                       WELTWEITES MANAGEMENT\0"
    "\0"
    "\0"
    "\0"
    "ALAN JOHNSON\0"
    "\0"
    "\0"
    "\0"
    "LEITUNG DIGITALPRODUKTION\0"
    "\0"
    "\0"
    "AUDIO-MANAGER\0"
    "\0"
    "\0"
    "KREATIVDIREKTOR\0"
    "MALCOLM CRUMMACK\0"
    "\0"
    "\0"
    "\0"
    "LEITER PRODUKTENTWICKLUNG\0"
    "\0"
    "\0"
    "STEVEN BROUMLEY\0"
    "TECHNISCHER LEITER\0"
    "\0"
    "RUSSELL BYRD\0"
    "\0"
    "\0"
    "\0"
    "GM DER ACCLAIM STUDIOS, AUSTIN\0"
    "\0"
    "        LEITUNG ACCLAIM STUDIOS, AUSTIN\0"
    "MARC SCHAEFGEN - LORD OF THE DEAD\0"
    "\0"
    "\0"
    "TITOS MENCHACA - TAL SET\0"
    "\0"
    "\0"
    "\0"
    "DOUG FORREST - BASTILLE\0"
    "JOSE BROWN - OBLIVION / GUARDIAN\0"
    "\0"
    "\0"
    "\0"
    "DAVID DIENSTBIER - CAMPAIGNER\0"
    "\0"
    "\0"
    "DAVID KRAUSE - FIREBORN / DINOSOIDS\0"
    "JESSICA ROBERTSON - SYRA\0"
    "\0"
    "\0"
    "\0"
    "TODD LOWE - PURLIN\0"
    "\0"
    "BERNADETTE NASON - ADON\0"
    "TRAVIS DAVIS - TUROK\0"
    "\0"
    "\0"
    "\0"
    "                       SPRECHER\0"
    "JUSTIN WITHERS\0"
    "\0"
    "SHANE TATE\0"
    "\0"
    "JIM STRONG\0"
    "\0"
    "BRANDON ROWLETT\0"
    "MARK RICHARDS\0"
    "\0"
    "\0"
    "CHRIS KENDALL\0"
    "\0"
    "\0"
    "JERREMY ARNSTON\0"
    "                                   TESTER\0"
    "\0"
    "\0"
    "RUSS BREWER\0"
    "PROJEKTLEITUNG\0"
    "\0"
    "TODD DOWD\0"
    "\0"
    "\0"
    "LEITER QS\0"
    "\0"
    "\0"
    "                           AUSTIN-QS\0"
    "\0"
    "\0"
    "\0"
    "JOHN HENKE\0"
    "\0"
    "MARC SCHAEFGEN\0"
    "\0"
    "DARREN MITCHELL\0"
    "                           SOUNDDESIGN\0"
    "\0"
    "BEY BICKERTON\0"
    "\0"
    "\0"
    "DAVID DIENSTBIER\0"
    "\0"
    "\0"
    "\0"
    "                       ZUSeTZLICHES DESIGN\0"
    "\0"
    "BRIAN WATSON\0"
    "\0"
    "\0"
    "\0"
    "DAVID SMITH\0"
    "ANDY ONEIL\0"
    "\0"
    "STEVAN HIRD\0"
    "STEVE BROUMLEY\0"
    "\0"
    "                   ZUSeTZLICHE PROGRAMMIERUNG\0"
    "\0"
    "\0"
    "DIGITAL IMAGING GROUP\0"
    "\0"
    "\0"
    "RYAN TRACY\0"
    "\0"
    "ALEX OMLANSKY\0"
    "\0"
    "\0"
    "PETER FRANCO\0"
    "\0"
    "\0"
    "\0"
    "SCOTT BROCKER\0"
    "\0"
    "\0"
    "                         ZUSeTZLICHES DESIGN\0"
    "\0"
    "\0"
    "\0"
    "ROB WHITAKER - DIGITALPRODUKTION\0"
    "\0"
    "\0"
    "\0"
    "ROBERT WILSHER - DIGITALPRODUKTION\0"
    "\0"
    "JEFF SHELTON - DESIGN\0"
    "\0"
    "\0"
    "ROBBIE MILLER - DIGITALPRODUKTION\0"
    "\0"
    "\0"
    "PAUL MASTERS - PROGRAMMIERUNG\0"
    "\0"
    "\0"
    "BRAD MARQUES - DIGITALPRODUKTION\0"
    "\0"
    "\0"
    "\0"
    "MARC MACKIN - DIGITALPRODUKTION\0"
    "TREVOR LEMOINE - DIGITALPRODUKTION\0"
    "\0"
    "MATT KYLE - PROGRAMMIERUNG\0"
    "\0"
    "MICHAEL HUEY - DESIGN\0"
    "\0"
    "\0"
    "NEILL GLANCY - DESIGN\0"
    "\0"
    "\0"
    "MICHAEL FONG - DIGITALPRODUKTION\0"
    "\0"
    "\0"
    "\0"
    "JIM COWLISHAW - PROGRAMMIERUNG\0"
    "\0"
    "BRUCE COONER - PROGRAMMIERUNG\0"
    "\0"
    "\0"
    "JASON BEHR - DESIGN\0"
    "MICHAEL DAUBERT\0"
    "KbNSTLERISCHE LEITUNG\0"
    "\0"
    "\0"
    "FRANCISCO JAVIER LAFUENTE\0"
    "\0"
    "\0"
    "PROGRAMMIERLEITUNG\0"
    "\0"
    "MARK PACINI\0"
    "PROJEKTMANAGER\0"
    "\0"
    "                           RAGE WARS TEAM\0"
    "\0"
    "\0"
    "\0"
    "\0"
    "\0"
    "\0";
