name: progress-report
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            versions/us/report.json
            versions/us-rev1/report.json
            versions/eu/report.json
            versions/eu-x/report.json
            versions/de/report.json
      - uses: actions/upload-artifact@v4
        with:
          name: us_report
          path: versions/us/report.json
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: us-rev1_report
          path: versions/us-rev1/report.json
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: eu_report
          path: versions/eu/report.json
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: eu-x_report
          path: versions/eu-x/report.json
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: de_report
          path: versions/de/report.json
          if-no-files-found: error
